### ISSUE TITLE
[WinPhone] Permission 'NONE' Ignored

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#109]
Type: BUG
PhoneGap Version: All
Devices: All

The config.xml has the following preference:
`<preference name="permissions" value="none"/>`

Android .apk picks that up correctly, but when .xap submitted to Windows Phone Dev Center it shows: 

ID_CAP_CONTACTS
ID_CAP_IDENTITY_USER
ID_CAP_ISV_CAMERA
ID_CAP_LOCATION
ID_CAP_MEDIALIB
ID_CAP_MICROPHONE
ID_CAP_NETWORKING
ID_CAP_SENSORS
ID_CAP_WEBBROWSERCOMPONENT
ID_HW_CAMERA
ID_HW_MAGNETOMETER 

Related issue:
http://community.phonegap.com/nitobi/topics/capabilities_for_windows_phone_devices_app_builded_on_cloud

**Comment by asifeqbal** [comment]
thanx mate....
