### ISSUE TITLE
[whitelist] subdomains true on config access not working on android

### ISSUE THREAD

**Issue by wildabeast** [phonegap/build#156]
See http://community.phonegap.com/nitobi/topics/access_elements_not_working_on_android

for more info.

**Comment by 3nGercog** [comment]
I have the same problem and nothing seems to work.

My meta tag:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';connect-src 'self'; img-src 'self' data: ; media-src *"`>

 My config.xml looks something like this:
```
<access origin="*" />
  <preference name="SplashScreen" value="screen" />
  <preference name="windows-target-version" value="8.1" />
  <allow-intent href="http://*/*" />
  <allow-intent href="https://*/*" />
  <allow-intent href="tel:*" />
  <allow-intent href="sms:*" />
  <allow-intent href="mailto:*" />
  <allow-intent href="geo:*" />
  <allow-navigation href="http://*/*" />
  <allow-navigation href="https://*/*" />
  <allow-navigation href="data:*" />
  <allow-navigation href="svn.aml.com.ua" />
```

Error messages:
[chromium] external/chromium/net/disk_cache/hostres_plugin_bridge.cc:52: [1009/113554:INFO:hostres_plugin_bridge.cc(52)] StatHubCreateHostResPlugin initializing...
[chromium] external/chromium/net/disk_cache/hostres_plugin_bridge.cc:57: [1009/113554:INFO:hostres_plugin_bridge.cc(57)] StatHubCreateHostResPlugin lib loaded
[chromium] external/chromium/net/disk_cache/hostres_plugin_bridge.cc:63: [1009/113554:INFO:hostres_plugin_bridge.cc(63)] StatHubCreateHostResPlugin plugin connected
[chromium] external/chromium/net/http/http_cache.cc:1168: [1009/113554:INFO:http_cache.cc(1168)] HttpCache::OnBackendCreated HostStat created
[chromium] external/chromium/net/disk_cache/stat_hub.cc:216: [1009/113554:ERROR:stat_hub.cc(216)] StatHub::Init - App io.cordova.garden8 isn't supported.
[chromium] external/chromium/net/disk_cache/hostres_plugin_bridge.cc:73: [1009/113554:INFO:hostres_plugin_bridge.cc(73)] netstack: Failed to find symbols in plugin: libdnshostprio.so
[chromium] external/chromium/net/disk_cache/stat_hub.cc:216: [1009/113554:ERROR:stat_hub.cc(216)] StatHub::Init - App io.cordova.garden8 isn't supported.

**Comment by wildabeast** [comment]
@3nGercog please open a discussion in the [support forum](https://forums.adobe.com/community/phonegap/build). Also I don't think that error log you're showing is related. More informative information would probably be in your javascript console by connecting the android developer tools to your phonegap app.

**Comment by 3nGercog** [comment]
@wildabeast I have apache cordova app. Can this affect the application?
