### ISSUE TITLE
Adding a splash screen preference mode that will not effect the entire application. 

### ISSUE THREAD

**Issue by Hyginus** [phonegap/build#170]
As apple do not support landscape splash screen, and also splash image bad behaviour on landscape mode in different devices. Adding a preference that could lock the splash screen on portrait and return the entire app to either landscape or portrait as well as default value will be a good idea.

**Comment by goya** [comment]
this functionality has been moved to the splashcreen plugin https://github.com/apache/cordova-plugin-splashscreen and is not handled by PhoneGap Build.
