### ISSUE TITLE
[Android] Include option for targetSDKversion

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#174]
There were a request from the community to include targetSDKversion in config.xml

Description:

%%%%%%%%%%%%%%%%%%%%%%

android:targetSdkVersion
    An integer designating the API Level that the application targets. If not set, the default value equals that given to minSdkVersion.

This attribute informs the system that you have tested against the target version and the system should not enable any compatibility behaviors to maintain your app's forward-compatibility with the target version. The application is still able to run on older versions (down to minSdkVersion).

As Android evolves with each new version, some behaviors and even appearances might change. However, if the API level of the platform is higher than the version declared by your app's targetSdkVersion, the system may enable compatibility behaviors to ensure that your app continues to work the way you expect. You can disable such compatibility behaviors by specifying targetSdkVersion to match the API level of the platform on which it's running. For example, setting this value to "11" or higher allows the system to apply a new default theme (Holo) to your app when running on Android 3.0 or higher and also disables screen compatibility mode when running on larger screens (because support for API level 11 implicitly supports larger screens).

There are many compatibility behaviors that the system may enable based on the value you set for this attribute. Several of these behaviors are described by the corresponding platform versions in the Build.VERSION_CODES reference.

To maintain your application along with each Android release, you should increase the value of this attribute to match the latest API level, then thoroughly test your application on the corresponding platform version.

%%%%%%%%%%%%%%%%%%%%%%

Please consider.

Original topic:
http://community.phonegap.com/nitobi/topics/when_is_android_targetsdkversion_number_on_phonegap_build_going_to_be_available

Thanks

**Comment by kgillespieanaren** [comment]
This feature does not work.

Repro:
Set in config.xml the following preference,

<preference name="android-targetSdkVersion" value="21" />

Run "phonegap build android"

Open "platforms/android/project.properties"

Note that in the project.properties file the following is stated,
"target=android-19"

Expected result,
"target=android-21"

**Comment by omnidan** [comment]
I agree with @kgillespieanaren - this feature does not work, even when I change project.properties (which I know you shouldn't do, but it doesn't get overwritten during the build process), it's still building for 19:
```
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
```
I also tried modifying AndroidManifest.xml to read `<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="21" />`, and of course my config.xml contains `<preference name="android-targetSdkVersion" value="21" /> <preference name="android-minSdkVersion" value="21" />`.

**Comment by wildabeast** [comment]
The `targetSdkVersion` is a *[PhoneGap Build](https://build.phonegap.com)* custom preference, and is only supported when you do remote builds on PGB. @ceefour, @kgillespieanaren, @omnidan, you appear to be doing local builds on your computer (i.e. `phonegap build android`) and so the `targetSdkVersion` preference has no context and will do nothing.

Possible solution for the cli: [phonegap android 3.7.1 sets the target-sdk to android-21 by default].(http://cordova.apache.org/announcements/2015/02/06/cordova-android-3.7.1.html)

Note that this issue tracker is for issues with PhoneGap Build -- for issues with the phonegap cli such as changing your sdk target, you'll get better assistance at, 
- [the PhoneGap google group](http://groups.google.com/groups/phonegap)
- [Stackoverflow.com](http://stackoverflow.com/questions/tagged/cordova)
