### ISSUE TITLE
[Android] HTML5 Video cannot be played (probably after #173)

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#185]
Missing manifest configuration causing HTML5 video and (possibly) 2D rendering operation to fail on a signed app. Debug app works fine.

Missing attribute:
`android:hardwareAccelerated="true"`

**Comment by adetheprince** [comment]
Hello there and everyone.
I am sure its late to comment on here but I am having the exact problem.
I managed to build the apk  file from a html simple page that have index/js /css .
The  site with video tag links mp4 , this worked fine with PhoneGap tool and tested on my browser ( andropid, PC, Appl. ) using 192.168.1.100:3000 all worked fine but after converting this to apk no video is playing and I have an icon on the left top corner like image error.

Herer is what i tried but to no avail.


<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="info.satdoc.dyndns.satIPTV" version="1.0.0">
  <name>Dociptv</name>
  <description>Hello World sample application that responds to the deviceready event.</description>
  <author href="http://phonegap.com" email="support@phonegap.com">PhoneGap Team</author>
  <content src="index.html"/>
 


<preference name="AllowInlineMediaPlayback" value="true" />

    <feature name="http://api.phonegap.com/1.0/battery"/>
    <feature name="http://api.phonegap.com/1.0/camera"/>
    <feature name="http://api.phonegap.com/1.0/contacts"/>
    <feature name="http://api.phonegap.com/1.0/file"/>
    <feature name="http://api.phonegap.com/1.0/geolocation"/>
    <feature name="http://api.phonegap.com/1.0/media"/>
    <feature name="http://api.phonegap.com/1.0/network"/>
    <feature name="http://api.phonegap.com/1.0/notification"/>
 <access origin="http://phonegap.com" subdomains="true" />


 <preference name="orientation" value="default"/>
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="true"/>
 



<application android:hardwareAccelerated="true">





I also disallow them but no different , video list shows, all links shows, but no picture no sound.
Its like something is blocking any url links playback once is converted to apk using any program, phonegap and even other like Quick-App-v1.1.
My html pages works fine on android and apple phones, just the apk dont work and annoying me for the last 5 days.lol
