### ISSUE TITLE
[Android] Error when hydrating app

### ISSUE THREAD

**Issue by jjustin3** [phonegap/build#187]
When hydrating my app, I receive the error:
"org.json.JSONObject$1 cannot be cast to java.lang.String"

I have tried "dehydrating" the app, rebuilding it, hydrating it, and then rebuilding and testing but nothing seems to work. I have looked around but not found this error occurring with anyone else. Any advice would be appreciated. Thanks.

**Comment by moto-geek** [comment]
same issue, my AppID is "919722"
