### ISSUE TITLE
[iOS] Add support to new iOS 7 icons

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#196]
Warnings due to missing recommended icon size. This icon size introduced to support iOS7

Warning Message:
Missing recommended icon file - The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format. 

Original Thread:
http://community.phonegap.com/nitobi/topics/missing_recommended_icon_file

**Comment by sukanta-ciem** [comment]
Hi,
@bobeast , i am facing the same issue during uploading my .ipa file through application loader. my app id is 2756331. Can you help me please.
