### ISSUE TITLE
Splash screens are not picked up correctly on landscape orientation

### ISSUE THREAD

**Issue by dotnetwise** [phonegap/build#198]
``` xml
  <gap:splash gap:platform="android" src="res/screen/android/screen-ldpi-portrait.png" width="200" height="320" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-mdpi-portrait.png" width="480" height="320" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-hdpi-portrait.png" width="480" height="800" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-xhdpi-portrait.png" width="720" height="1280" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-ldpi-landscape.png" width="320" height="200" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-mdpi-landscape.png" width="320" height="480" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-hdpi-landscape.png" width="800" height="480" />
  <gap:splash gap:platform="android" src="res/screen/android/screen-xhdpi-landscape.png" width="1280" height="720" />
```

Only portrait screens will be picked up at any given time and when your device orientation is `landscape` the splash screens will be `stretched/distort`

The correct `portrait splash`:
![image](https://f.cloud.github.com/assets/485535/1173309/e60c98a2-2135-11e3-843f-ef6c3bd0cb9d.png)
The correct `landscape splash`:
![image](https://f.cloud.github.com/assets/485535/1173315/fb4ef098-2135-11e3-9c8f-313f4ae90595.png)
The **incorrect** phonegap splash when orientated `landscape`
![image](https://f.cloud.github.com/assets/485535/1173327/21de9dbc-2136-11e3-8f55-b06bd56badf7.png)
The correct phonegap splas when orientated `portrait`
![image](https://f.cloud.github.com/assets/485535/1173345/6a7d6d1e-2136-11e3-9beb-8dcf79062558.png)

**Comment by jiehou** [comment]
Hello, 
today I tried a simple App. I built the Android-App using PhoneGap Build. The splash page still has problem under landscape mode. Below is my config.xml. I want to ask whether this bug has been fixed or not?
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.phonegap.helloworld" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>Hello World</name>
    <description>
        Hello World sample application that responds to the deviceready event.
    </description>
    <author email="support@phonegap.com" href="http://phonegap.com">
        PhoneGap Team
    </author>
    <content src="index.html" />
    <preference name="permissions" value="none" />
    <preference name="orientation" value="default" />
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="true" />
    <preference name="android-minSdkVersion" value="10" />
	<preference name="SplashScreen" value="screen"/>
	<preference name="SplashScreenDelay" value="10000" />

	<gap:plugin name="org.apache.cordova.splashscreen" />
	<gap:plugin name="com.boyvanderlaak.cordova.plugin.orientationchanger" version="0.1.1" />
	
	
	<gap:splash src="res/screen/android/screen-ldpi-portrait.png"  gap:platform="android" gap:qualifier="port-ldpi" />
	<gap:splash src="res/screen/android/screen-mdpi-portrait.png"  gap:platform="android" gap:qualifier="port-mdpi" />
	<gap:splash src="res/screen/android/screen-hdpi-portrait.png"  gap:platform="android" gap:qualifier="port-hdpi" />
	<gap:splash src="res/screen/android/screen-xhdpi-portrait.png"  gap:platform="android" gap:qualifier="port-xhdpi" />

	<gap:splash src="res/screen/android/screen-ldpi-landscape.png" gap:platform="android" gap:qualifier="land-ldpi"/>
	<gap:splash src="res/screen/android/screen-mdpi-landscape.png" gap:platform="android" gap:qualifier="land-mdpi"/>
	<gap:splash src="res/screen/android/screen-hdpi-landscape.png" gap:platform="android" gap:qualifier="land-hdpi"/>
	<gap:splash src="res/screen/android/screen-xhdpi-landscape.png" gap:platform="android" gap:qualifier="land-xhdpi"/>
	<gap:splash src="splash.png" />
</widget>
Thanks very much in advance!
Jie

**Comment by dnwts** [comment]
@jiehou Maybe you should reopen this issue or create a new one?
