### ISSUE TITLE
The page you were looking for doesn't exist. 

### ISSUE THREAD

**Issue by shawnmckay24** [phonegap/build#204]
http://community.phonegap.com/nitobi/topics/the_page_you_were_looking_for_doesnt_exist-pbgha

Am having a problem with testers that seems to be related to the Adobe ID vs GitHub id. When they visit the install page link if they registered with Adobe ID and also linked GitHub, and the email address used on the add collaborators screen matches their GitHub ID, when they visit the install page they get the nice red "the Page you were looking for doesn't exist" error. 

The session handling seems glitchy in this area.

**Comment by rodneyworkman291** [comment]
My testers are having this issue. Looks like this issue was closed last year.  Having trouble getting this release to my testers.
