### ISSUE TITLE
[iOS] Expose CFBundleVersion in Config.xml

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#229]
User are experiencing use submitting app due to invalid CFBundleVersion - Build Number. Error message as follow:

_This bundle is invalid. The value for key CFBundleVersion [1.0.1] in the Info.plist file must contain a higher version than that of the previously uploaded version [XXX]._

Original Topic:
http://community.phonegap.com/nitobi/topics/inability_to_specify_build_version_for_ios
http://community.phonegap.com/nitobi/topics/build_number_cfbundleversion_for_ios_app

**Available workaround from John Scott**
1) Download and unzip the IPA file.
2) Click on MyApp.app and "Expand Package Contents".
3) Open the info.plist file in XCode and edit the "Bundle version" key.
4) Resign via these instructions: https://coderwall.com/p/cea3fw

**Comment by plan-reduc** [comment]
hello, i got this issue too, the problem is not solved in PGB, i have made all change that i could do but my version wont change and stay at "1.2.5" in info.plist

<gap:config-file platform="ios" parent="CFBundleVersion">
<string>1.2.6</string>
</gap:config-file>

<gap:config-file platform="ios" parent="CFBundleShortVersionString">
<string>1.2.6</string>
</gap:config-file>

widget version="1.2.6" versioncode etc...

**Comment by wildabeast** [comment]
@plan-reduc I can't read your sample code, you need to escape it.

If you give me your PhoneGap Build App ID, I can have a look.

**Comment by plan-reduc** [comment]
hello, it seems to be corrected, the issue was from the PGB, during the last day he don't update every of my new zip that i have uploaded, i was in obligation to delete my project and send new one every time i need to update my build, now the issue is solved... thanks

**Comment by MaicolBen** [comment]
I tried the workaround of @jhnsctt but I don't have `ResourceRules.plist` and `Entitlements.plist`files. What are missing?

**Comment by aesculus** [comment]
This did the trick for me an only changed the build number allowing me to keep the version number.
<gap:config-file platform="ios" parent="CFBundleVersion">
    <string>517</string>
</gap:config-file>
