### ISSUE TITLE
[Docs] Remote collaboration and Testing

### ISSUE THREAD

**Issue by shazron** [phonegap/build#246]
Question: 
Unless I'm missing something, wondering why this info is here:
http://docs.phonegap.com/en/edge/guide_phonegap-build_test_index.md.html#Remote%20Collaboration%20and%20Testing

instead of here: 
http://docs.build.phonegap.com/en_US/3.1.0/index.html

If its already there on the Build docs, I apologize - but if it's not easily found, then that's a problem as well.

**Comment by goya** [comment]
doc website has been amalgamated with the phonegap.com build site.  the docs above have been deprecated.
