### ISSUE TITLE
[iOS] Device orientation configuration not working as expected

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#263]
iOS didn't obey `<preference name="orientation" value="potrait" />` or `<preference name="orientation" value="landscape" />`

It will always behave as default (both landscape and portrait are enabled).

**Comment by bau720123** [comment]
hi guys
I tried many times in PGB 3.7 (build.phonegap.com) and ios 8.1.3
it is fully work !!!

step 1，remove this plugin (if use this plugin，the "orientation" will change back to default mode)
https://github.com/yoik/cordova-yoik-screenorientation/blob/06b93e6/README.md

step 2，"portrait" and "landscape" are all work done

**Comment by LukaszC** [comment]
Hi Guys,

I don't think it is fixed/works. This is important to notice that bug concerns iPads only, on iPhones it seems to work. Then once again:
* cordova version: `4.3.0`
* config.xml: `<preference name="Orientation" value="landscape" />`
* iPhone6 emulator (iOS 8.2): works as expected, emulator rotated to landscape by default, landscape view preserved when manually rotated to portrait
* iPadAir emulator (iOS 8.2): does not work as expected, emulator is not rotated to landscape by default, view is adjusted to portrait, where expected behaviour (by me) was like with the iPhone6

**Comment by zigzag-way** [comment]
I still cannot force my app to use only portrait mode
My config section is:
    <gap:config-file platform="ios" parent="UISupportedInterfaceOrientations" overwrite="true">
        <array>
            <string>UIInterfaceOrientationPortrait</string>
        </array>
    </gap:config-file>

**Comment by xlozinguez** [comment]
FWIW here's how I specified which mode to allow and disable based on device and else: 
I abandonned the idea to specify anything in the config.xml and instead I dropped a `modify_plist.sh` file into `hooks/after_prepare` and it says:
```
#!/bin/bash

PLIST=platforms/ios/*/*-Info.plist

cat << EOF |
Add :UISupportedInterfaceOrientations array
Add :UISupportedInterfaceOrientations: string UIInterfaceOrientationPortrait
Add :UISupportedInterfaceOrientations: string UIInterfaceOrientationPortraitUpsideDown
Add :UISupportedInterfaceOrientations: string UIInterfaceOrientationLandscapeLeft
Add :UISupportedInterfaceOrientations: string UIInterfaceOrientationLandscapeRight
Add :UISupportedInterfaceOrientations~ipad array
Add :UISupportedInterfaceOrientations~ipad: string UIInterfaceOrientationPortrait
Add :UISupportedInterfaceOrientations~ipad: string UIInterfaceOrientationPortraitUpsideDown
EOF
while read line
do
    /usr/libexec/PlistBuddy -c "$line" $PLIST
done

true
```

now build your app and voilà! you can adjust this to your needs...

**Comment by jdinse** [comment]
Folks, I have a solution that worked for me. As some of you like @LukaszC reported, it works for iPhone but not for iPad. This is because iPad needs an extra configuration as it is [documented by Apple](https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW10).

That means, you have to provide ``UISupportedInterfaceOrientations~ipad`` as well. In my case using Intel XDK it looks like this:

```
<config-file target="*-Info.plist" parent="UISupportedInterfaceOrientations" overwrite="true">
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
</config-file>

<config-file target="*-Info.plist" parent="UISupportedInterfaceOrientations~ipad" overwrite="true">
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
</config-file>
```

So, if you're using PhoneGap I should be look like this:
```
<gap:config-file platform="ios" parent="UISupportedInterfaceOrientations" overwrite="true">
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
</gap:config-file>

<gap:config-file platform="ios" parent="UISupportedInterfaceOrientations~ipad" overwrite="true">
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
</gap:config-file>
```

**Comment by mix3d** [comment]
Thanks @xlozinguez , you're a lifesaver! Not using phonegap, but the Cordova CLI wasnt taking the orientation properly; but thanks to this script I'm all set! Woo!

**Comment by gsanjeevkumar** [comment]
I am using Ionic, do you guys have a solution for this please.

**Comment by luchens** [comment]
Any solution? Thanks!

**Comment by gerhardcit** [comment]
Using the latest:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.4
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.3 Build version 7D175

Today still, the Device orientation is not handled.

Xcode report this:
....Plugins/cordova-plugin-splashscreen/CDVSplashScreen.m:330:62: 'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

And I have to manually set the device orientation in Xcode when building. Any change Cordova or Ionic guys can get this to work. It's a fairly basic option, isn't it?

**Comment by alec-implicitdesign** [comment]
Honestly, is there still no single, working way to do this?

**Comment by Gilead** [comment]
@alec-implicitdesign 

    <platform name="ios">
        <config-file mode="replace" parent="UISupportedInterfaceOrientations" target="*-Info.plist">
            <array>
                <string>UIInterfaceOrientationPortrait</string>
            </array>
        </config-file>
        <config-file mode="replace" parent="UISupportedInterfaceOrientations~ipad" target="*-Info.plist">
            <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationPortraitUpsideDown</string>
            </array>
        </config-file>
...
