### ISSUE TITLE
Plugins with precompiled binary code

### ISSUE THREAD

**Issue by maxmoore14** [phonegap/build#281]
My understanding is that plugins submitted that use precompiled code will be rejected. I assume this is due to security risks associated with random, unpublished code.

Is it possible to include a plugin in my project somewhere - perhaps outside the www folder in a "plugins" folder or something like that? That way I am accepting the risk for my app without exposing the whole community by publishing the plugin.

**Comment by goya** [comment]
no longer relevant, precompiled code is now accepted.
