### ISSUE TITLE
Support Private Git Server Other Then Github

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#285]
Support private git server other then Github such as GitLab, BitBucket

**Comment by Spone** [comment]
Hi @amirudin there are 33 votes from the community. http://community.phonegap.com/nitobi/topics/support_private_git_repositories_other_than_github
Do you have a roadmap for this feature?
Thanks

**Comment by aplimovil** [comment]
+1

**Comment by jgmio** [comment]
+1

**Comment by mfilotto** [comment]
:+1:

**Comment by Omnem** [comment]
+1

**Comment by jessemonroy650** [comment]
+1

**Comment by pocheptsov** [comment]
+100500

**Comment by goya** [comment]
we currently support gitlab, github and bitbucket. 

due to security concerns about storing private ssh keys for custom, private github servers we probably wont be supporting non-oauth supported clients anytime soon.
