### ISSUE TITLE
iOS hotspot/in-call status bar

### ISSUE THREAD

**Issue by barbarNik** [phonegap/build#292]
We have a problem with iOS in-call/hotspot status bar - it's pushing the application down, and it seems, that there is no event for that .

Related questions on StackOverflow:
http://stackoverflow.com/questions/22697925/stop-phonegap-app-from-scrolling-when-call-hotspot-indicator-is-visible
http://stackoverflow.com/questions/21619829/prevent-ios-in-call-status-bar-from-pushing-phonegap-uiwebview-offscreen

**Comment by triasrahman** [comment]
any update for this?
