### ISSUE TITLE
Icon copied to www root

### ISSUE THREAD

**Issue by maxmoore14** [phonegap/build#297]
PhoneGap Build is copying one of the iOS icons to the www folder - specifically "Icon-76_at_2x.png".

I have no idea why it would be doing this, but I can speculate that an older version of iOS has a bug that requires it to be there and this was a fix for it.

In any event, this is being copied across all platforms - not just iOS - and that certainly seems like a bug (albeit a small one).

My suggestions are:

1. If it is not there on purpose, stop copying it.
2. If it is there for a specific version of iOS, check the `<preference name="deployment-target" />` tag for appropriate use cases.
3. Never copy for platforms other than iOS.

**Comment by goya** [comment]
fixed.

**Comment by bau720123** [comment]
hi everybody and @goya 
problem solved
thanks @goya
