### ISSUE TITLE
Build for Firefox OS

### ISSUE THREAD

**Issue by rebrandsoftware** [phonegap/build#324]
I would like to build for Firefox OS with PhoneGap build.

In searching the community posts I saw that Amir asked that a feature request be posted here on GitHub, but as far as I can tell that was never done.

http://community.phonegap.com/nitobi/topics/is_there_any_way_to_use_phonegap_build_to_create_a_firefox_os_app

Well, now it's done!  :)

**Comment by jessemonroy650** [comment]
Mozilla has decided to stop firefox OS.
- Techcrunch - [Mozilla Will Stop Developing And Selling Firefox OS Smartphones](http://techcrunch.com/2015/12/08/mozilla-will-stop-developing-and-selling-firefox-os-smartphones/)

**Comment by goya** [comment]
like jesse said
