### ISSUE TITLE
[Forum] Integrate AdobeID With GetSatisfaction Login. 

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#325]
Using GetSatisfaction FastPass there is a chance to integrate AdobeID Single Sign-On into Getsatisfaction Forum:
https://getsatisfaction.com/nitobi/admin/fastpasses

Related request:
https://getsatisfaction.com/nitobi/topics/why_cant_phonegap_build_remember_that_im_logged_in

**Comment by goya** [comment]
we moved forum providers.
