### ISSUE TITLE
[Build] Debug fail if hydration turned on under PhoneGap 3.5

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#339]
Device fail to connect to Weinre server if hydration turned on in PhoneGap 3.5.

Following sample app reproduce the problem: AppID 1044397

**Comment by IvanRave** [comment]
Device fail to connect to Weinre server if hydration turned on in PhoneGap 3.6.3

Standard debug server on PhoneGap Build site

tested with https://github.com/phonegap/phonegap-start

debugging works without Hydration
