### ISSUE TITLE
Enhancement for Altering AndroidManifest.xml after plugin changes are applied

### ISSUE THREAD

**Issue by JohnWeidner** [phonegap/build#355]
The current gap:config-file element is great for when you need to add something to your AndroidManifest.xml file.   However, there currently isn't a way to remove elements from the config file.   

(I currently need to do this when I use the standard org.apache.cordova.media plugin.   This plugin adds all the permissions that are required to use ALL of the plugins capabilities.   However, all I am using the plugin for is to play a simple sound file.    Currently, I end up taking the .apk file that PGB builds, unpackage the apk file with apktool.   Replace the AndroidManifest.xml with my version that has the unnecessary permissions removed.   Rebuild the apk file with apktool.   Re-sign the file with jarsigner.   And finally zipalign the .apk file.)

Although my current need is for removing specific "uses-permission" elements, a generic mechanism for removing any elements might be helpful in the future.   Maybe a "delete" attribute could be added to the gap:config-file element that allows you to delete certain elements.   For example:

```
<gap:config-file platform="android" parent="manifest" delete="true"> 
       <uses-permission android:name="android.permission.RECORD_AUDIO" />
</gap:config-file>
```

**Comment by j4ml3t** [comment]
It doesn't work for me. I'm using cordova and I put it in AndroidManifest.xml, but after build the app, the permission which were supposed to be removed are still there.

**Comment by JohnWeidner** [comment]
@wildabeast The enhancement you mentioned on Nov 13, 2014 doesn't appear to exist anymore.  Is there a new way to have a plugin not add certain permissions to the AndroidManifest.xml file?   Or to remove them if they've been added?

**Comment by wildabeast** [comment]
@JohnWeidner what PhoneGap version are you using? Try using `edit-config` instead, its a similar implementation. Here's the [spec](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config), and you can find some examples by [searching the forum](https://forums.adobe.com/search.jspa?q=edit-config&place=%2Fplaces%2F4970418&depth=ALL) for "edit-config".
