### ISSUE TITLE
iOS plugin bundles not found when building

### ISSUE THREAD

**Issue by yimingkuan** [phonegap/build#368]
Some apps fail to build due to CpResource errors such as this: `CDVCapture.bundle: No such file or directory`

This only appears on iOS, Android and Windows Phone doesn't appear to be affected.

Test app to recreate the issue: 585587

**Comment by AnbuIOS** [comment]
HI Team,

While Build the ios mobile  applcation in xcode "resources/cvcapture.bundle no such file or directory" error occured .

screenshot attached.

kindly provide the sollution to fix this issue.

![ios error](https://cloud.githubusercontent.com/assets/20415344/16762782/a4b0b4aa-4843-11e6-8f1c-f050905605ff.png)
Thanks
