### ISSUE TITLE
[Android] Build doesn't set the default icon in /res/drawable

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#383]
The default icon isn't set as the default icon on Android, but instead is used on ldpi/mdpi/hdpi/xhdpi
and then overwritten by the other dpi images so the image in /res/drawable (default icon) is still Cordova icon.

Reproducible, confirmed with apktool.
AppID 1201975
Related Topic: https://getsatisfaction.com/nitobi/topics/default-icon-is-replaced-by-phonegap-icon-on-android

**Comment by jpierront** [comment]
Hello, any news ? Thx.

**Comment by Frankx7** [comment]
Looking forward to know if this is being planned at all? Been waiting for months

**Comment by goya** [comment]
fixed.
