### ISSUE TITLE
Change branch/tag via developer API

### ISSUE THREAD

**Issue by marcusds** [phonegap/build#387]
When creating a build via the developer API and using pull:true, we should be able to set the branch or tag that build will come from. (Maybe not even change the value in PGB, but use it for just that one build.)

Right now you have to go manually change the branch/tag in PGB any time you want it changed as the API seems to only support setting the tag value on app creation.

**Comment by goya** [comment]
tag has now been added to the api for update.

http://docs.build.phonegap.com/en_US/developer_api_write.md.html#_put_https_build_phonegap_com_api_v1_apps_id
