### ISSUE TITLE
[Docs] Fix Icons and Splash Screens src relative path

### ISSUE THREAD

**Issue by msokk** [phonegap/build#388]
The docs currently say:
`src: (required) specifies the location of the image file, relative to your www directory`
in [PhoneGap Build Docs](http://docs.build.phonegap.com/en_US/configuring_icons_and_splash.md.html#Icons%20and%20Splash%20Screens)

It should be `relative to your project directory`
as stated in [Cordova Docs](http://cordova.apache.org/docs/en/4.0.0/config_ref_images.md.html#Icons%20and%20Splash%20Screens) and discussed [PhoneGap Build Support ticket](http://community.phonegap.com/nitobi/topics/icons-splash-screens-working-only-either-in-local-or-remote-builds?utm_source=notification&utm_medium=email&utm_campaign=new_comment&utm_content=reply_button&reply[id]=15108888#reply_15108888)

This should make unifiying icons between local and remote builds easier.

**Comment by goya** [comment]
splashes and icons should be relative to the config.xml, docs have been updated to state this.
