### ISSUE TITLE
[Build] .pgbomit ignored on git-based repo.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#399]
Build seems to ignore .pgbomit on a git repo. Zip upload work fine.

Reproducible with Github & Bitbucket origin.

Sample app: https://github.com/amirudin/PhoneGapPluginDemo/tree/pgomit

**Comment by dmytro-shchurov** [comment]
Don't you think guys it's quite critical issue which leads to not working build results? There are no any response in 13 days already...

**Comment by goya** [comment]
unable to reproduce. even with the test repository. do you have an app id that is showing this behaviour?

**Comment by dmytro-shchurov** [comment]
Sure, I have. AppID 763767. `.pgbomit`contains a list of files and folders I'd like to not see in the result *www* folder, but they are there. Paths on this list consider a final folder structure, as it was advised by someone from the support team, and this worked before(!).  
Just made a fresh build, and the problem is still there.
The web app is in `repo_root/src/www`. Then this `www` folder is pop up, and everything else is put from `repo_root` *into* this folder. This is insane IMHO.

**Comment by goya** [comment]
.pgbomit is just a filename placeholder we don't read it's contents. it's not like a .gitignore file

we just remove the folder and everything under where it is placed.

**Comment by gobbo712** [comment]
it is not working in my setup. no matter where I put the .pgbomit file all resources are in the compiled .apk

**Comment by goya** [comment]
hi @gobbo712  - please start a conversation at community.phonegap.com so we can troubleshoot your issue.

**Comment by gobbo712** [comment]
my issue is that .pgbomit does not work at all, all my unwanted resources are included in the final pak no matter where I put the .pgbomit file. I tried several times and never worked.

**Comment by gobbo712** [comment]
I left a comment in http://community.phonegap.com/nitobi/topics/-pgbomit-settings-are-ignored. where this bug is referenced as the bug track for this issue, the topic in the community is in progress but this bug is closed.

**Comment by goya** [comment]
are you the user with the username"customer" on this issue? please post your app id on community.phonegap.com so we can try and replicate.

**Comment by gobbo712** [comment]
I am not using github for my app. As I said I got here coming from the phonegap community, so I expect this issue (bug) is independent from github. maybe I am wrong... I guess I am mr customer :)

**Comment by gobbo712** [comment]
I cannot post my app in github as I am working on a commercial app for the company I work for....

**Comment by goya** [comment]
please make a new app that demonstrates your issue and post the app id on community.phonegap.com so we can troubleshoot.  as otherwise we cannot reproduce your issue.
