### ISSUE TITLE
Support for Android Apps / APK Localization (strings.xml)

### ISSUE THREAD

**Issue by regnete** [phonegap/build#401]
Android Apps (APK) build with PGB do not contain any localization files. Because of this, the google play store marks them as "available in standard locale only".

For iOS Apps (IPA) a simple mechanism is offered by PGB. Place local.strings files in locale specific folders below www folder like this:
 
-- www
--- locales
---- en
----- local.strings

The content of the local.strings files may be :
  "DummyKey" = "Dummyvalue"; 

The iOS solution is described here: http://community.phonegap.com/nitobi/topics/problem_with_binary_details_ios_localization_builded_with_phonegap_build

We need a comparable android solution. We could e.g. place an additonal folder tree below www folder:
 
-- www
--- res
---- values
----- strings.xml
---- values-en
----- strings.xml
---- values-de
----- strings.xml 

PGB should then copy the res folder one level up when assembling the apk. The folder could be identified by ist name "res" (as it is done for the above mentioned iOS solution for the name "locales") or by a special configuration tag/directive in config.xml (see #386 ) which is obviously the smarter solution.

**Comment by bmoshergit** [comment]
Thank you for requesting this Regnete!

**Comment by azabala** [comment]
+1...its a must to build localized apps for Google Play

**Comment by jumanji27** [comment]
+1 )

**Comment by bheijns** [comment]
+1!

**Comment by alexkvak** [comment]
+1

**Comment by Omnem** [comment]
+1

**Comment by roidayan** [comment]
+1

**Comment by kentmw** [comment]
+1

**Comment by bau720123** [comment]
+1

**Comment by sdrubish** [comment]
+1

**Comment by Luigi123** [comment]
+1

**Comment by Reon90** [comment]
+1

**Comment by wildabeast** [comment]
PGB has added beta support for Android localization files. To add, create directory locales/android/ in the root of your PGB application zip / repo, and place your localization files there. The contents will be copied into the Android res/ directory, and any nested sub-directory structures will persist. Here's an example of how these files will be compiled into your APK:

    <www.zip>/locales/android/values-fr/strings.xml --> <android_apk>/res/values-fr/strings.xml
    <www.zip>/locales/android/xml/custom.xml        --> <android_apk>/res/xml/custom.xml

Existing directories will be merged, but at this time any individual files you include will overwrite their target if it exists, so if any of your plugins have matching localization files, you'll need to merge them into your own locales directory manually.

Note that its a beta feature; try it out and let us know.

**Side note**: it seems to be implied above that adding localization files will add that to your supported locales in the Play store, however from my research and testing, the contents of your translation files will not affect this, you must [manually select your locales when uploading your app](http://www.oneskyapp.com/blog/how-to-add-localized-app-description-to-google-play/).

**Comment by bau720123** [comment]
hi @wildabeast 
could I ask..

when in iOS，the local.strings content is => "DummyKey" = "Dummyvalue";
so when in ndroid，is the strings.xml or custom.xml have any default value ?

**Comment by wildabeast** [comment]
@bau720123 the default content is whatever is created by the cordova cli, [which you can see here](https://github.com/apache/cordova-android/tree/master/bin/templates/project/res). strings.xml and custom.xml are just examples ... you can add whatever files you need. check out the [android resource docs](http://developer.android.com/guide/topics/resources/providing-resources.html) for what you might want to have in the `res/` directory.

as mentioned in the iOS notes above, if you're only using iOS locales you can put your content in either `locales/` or `locales/ios/`.

**Comment by bau720123** [comment]
ok
thanks @wildabeast

**Comment by wildabeast** [comment]
Closing re above solution.

**Comment by elbidone** [comment]
Hi, @wildabeast is this "beta" support continues ? I've tested with on PGB with cli-6.1.0 it works for android but cannot do it work for iOS. 

I'm trying to localize app_name adding local.strings files

-- www
--- locales
---- ios
----- pt
------ local.strings
----- en
------ local.strings

The content of the local.strings file are :
"CFBundleDisplayName" = "Brasil";
"CFBundleName" = "Brasil";
and 
"CFBundleDisplayName" = "England";
"CFBundleName" = "England";

Should I add stg on config.xml ? I've tried adding following config without success:

```xml
			<config-file parent="CFBundleLocalizations" mode="replace"> 
			    <array>
			      <string>pt</string>
			      <string>en</string>
			    </array>
			</config-file>
```
Thanks for your help

**Comment by elbidone** [comment]
I've opened a [ticket concerning this issue](https://forums.adobe.com/thread/2167742) to adobe support

**Comment by jskrepnek** [comment]
@wildabeast Hi, can you comment on continued support for the beta feature you [describe above](https://github.com/phonegap/build/issues/401#issuecomment-156537511) or suggest alternatives if it is no longer supported with newer versions of PGB?

There does not seem to be support for the `resource-file` element.
