### ISSUE TITLE
Orientation or Background-color problem

### ISSUE THREAD

**Issue by ahipki** [phonegap/build#404]
Hello everyone, 

I have a problem with my project. Building it with adobe build, on a Asus Nexus 7 and samsung S3, the background-color is white instead of orange but the orientation is landscape, what I want for the orientation. With a Samsung S5, the color is orange but the application can rotate.
What I want it's a orange background-color and a landscape orientation without any rotation possible.
Do you have an idea for this problem ?
Config.xml :
    < preference name="orientation" value="landscape" / >
Index.css :
body{
background-color:#ff8b00;
}

Thank you,

Annie.

**Comment by goya** [comment]
Please go to our support forums at http://community.phonegap.com so we can troubleshoot your issue.

the cordova google group would also be a good place to get help.
