### ISSUE TITLE
[iOS] Push Notification Code Include By Default

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#406]
Apple issue a warning to all apps regarding this:

"Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API."

Found related Apache Issue: https://issues.apache.org/jira/browse/CB-8084

** Please consider to merge onto PGB once above resolved.

**Comment by wildabeast** [comment]
This will be inherently fixed when we deploy PG 4.0, once its released by the Cordova team.

**Comment by nhoizey** [comment]
Still having this issue nowadays…
