### ISSUE TITLE
[Plugin] Unable to submit plugin - Error: No plugin.xml file found in root of repository

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#407]
Not able to submit Plugin for testing. 

Repo URI: https://github.com/amirudin/phonegap-facebook-plugin
Branch: PGBSubmitTrial or Master
Error: No plugin.xml file found in root of repository
My AdobeID: amirudin dot mohamedghani at customware dot net

Original topic: https://console.getsatisfaction.com/nitobi/conversations/how-to-upgrade-facebookconnect-to-0-11-0

**Comment by amirudin** [comment]
![cannot-submit-plugin](https://cloud.githubusercontent.com/assets/995594/6149941/35af5cca-b247-11e4-8cc4-c8adecbced4d.png)

**Comment by goya** [comment]
unable to replicate.  may have been fixed.
