### ISSUE TITLE
[WinPhone] Add support to WP 8.1 SDK

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#409]
PhoneGap Build currently uses WP8.0 SDK + Packaging tool.

**Comment by amirudin** [comment]
Original topic: https://getsatisfaction.com/nitobi/topics/windows-phone-8-1-not-being-built

**Comment by simonpapworth6742** [comment]
Is there anything I can do to help with this?

**Comment by wildabeast** [comment]
In the coming months we will likely be migrating build over to the [cordova-windows](https://github.com/apache/cordova-windows) implementation, from the current [cordova-wp8](https://github.com/apache/cordova-wp8). I'm naively guessing this will include updating to the 8.1 SDK.

Can you clarify what's blocking you here though? As our current cordova-wp8 builds should be supported by Windows Phone 8.1.

**Comment by goya** [comment]
windows 8 has been deprecated and we recommend moving to the windows platform.
