### ISSUE TITLE
PGB 3.7 miss the following ios's splash screen size 

### ISSUE THREAD

**Issue by bau720123** [phonegap/build#411]
according to this
http://community.phonegap.com/nitobi/topics/pgb-3-6-3-miss-the-following-ioss-splash-screen-size
PGB 3.7 miss the following ios's splash screen size

**Comment by amirudin** [comment]
+1

**Comment by bau720123** [comment]
thanks @amirudin reply
it is really a problem

**Comment by bau720123** [comment]
no any update or information...
it is really a long time ago...

**Comment by amirudin** [comment]
Reproducible: https://github.com/amirudin/Phonegap-Splashscreen-Test

**Comment by bau720123** [comment]
thanks @amirudin

**Comment by swSSO** [comment]
Hi,
It seems the bug has not been solved... Did someone find any workaround? 
Thx!

**Comment by goya** [comment]
don't use 3.7.0.  it shall be deprecated soon and removed from PhoneGap Build.

**Comment by bau720123** [comment]
thanks @goya 
for now I am using PGB cli-6.4.0 for a long period of time
