### ISSUE TITLE
Ajax request dont work after install on real device

### ISSUE THREAD

**Issue by 111crb111** [phonegap/build#413]
ajax request dont work after build, im develop with phonegap desktop app and moblie phonegap and when emulate on real device requests works fine but after build and install on that device ajax stop working. 

I make example app with ajax requests, seems like its dont works only with my rest api, but its works fine on desktop browser. 

build:
https://build.phonegap.com/apps/1331965/builds

zip:
https://drive.google.com/file/d/0B869Sv33xwGWMkVLaS1veTVWUnc/view?usp=sharing

**Comment by wildabeast** [comment]
What device are you testing on?

What error code / message does your request return?
