### ISSUE TITLE
Compiler issue using plugin from plugins.cordova.io while building for android 

### ISSUE THREAD

**Issue by kaushik947** [phonegap/build#415]
I get this error 

[javac] warning: /project/com.google.playservices/google-play-services_lib/libs/google-play-services.jar(com/google/android/gms/common/ConnectionResult.class): major version 51 is newer than 50, the highest major version supported by this compiler. 
[javac] It is recommended that the compiler be upgraded. 

in the log while using http://plugins.cordova.io/#/package/c... 
this plugin.Could you update the compiler on phonegap build???

**Comment by wildabeast** [comment]
We did get Java updated on our Android servers.
