### ISSUE TITLE
3rd plugin "nl.x-services.plugins.googleplus" build problem with PGB 3.7 

### ISSUE THREAD

**Issue by bau720123** [phonegap/build#417]
all detail right here

https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/43#issue

http://community.phonegap.com/nitobi/topics/3rd-plugin-nl-x-services-plugins-googleplus-build-problem-with-pgb-3-7

**Comment by bau720123** [comment]
hi pgb or cordova team
I notice that several 3rd plugins (not only "nl.x-services.plugins.googleplus") also have the same situation (xap file Confusion problem)
what's wrong with the PGB build ... ?

**Comment by wildabeast** [comment]
@bau720123 Unable to reproduce this -- do you have an App ID that's exhibiting this behaviour?

**Comment by bau720123** [comment]
hi @wildabeast 
my appid is 697726
http://www.littlebau.com/xap2.jpg

I notice that several 3rd plugins (not only "nl.x-services.plugins.googleplus") also have the same situation (xap file Confusion problem)

**Comment by bau720123** [comment]
hi @wildabeast 
anything update ?

**Comment by jessemonroy650** [comment]
@bau720123 Can we close this issue?

**Comment by bau720123** [comment]
oh!!!
sorry about that
it really a long ago...
