### ISSUE TITLE
[Android] Doesn't accept Package ID containing numeric characters.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#419]
Android build are no longer accepting Package ID containing numeric characters anywhere.

Example: com.phonegap123.testing will be converted to com.phonegap.build

Reproducible on PhoneGap 3.7.0

**Comment by wildabeast** [comment]
This is was actually done intentionally since numeric package id's were causing compile errors. However we should probably be simply leaving the error rather than changing it to a default.

**Comment by galaxymichael** [comment]
Hi wildabeast,

Thanks for confirming it's intentional. Is it possible to know when/if numbers in package Ids will be reallowed? I've a client unhappy at their ability to be able to update a live app in the Play store.

**Comment by goya** [comment]
should be fixed now.  please note that we are limited to the java format: 

/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/i

with no portions being java keywords.

**Comment by galaxymichael** [comment]
Brilliant, thanks. It now works again as it did and I can update the app.
