### ISSUE TITLE
no create_method specified: file or remote_repo

### ISSUE THREAD

**Issue by ashutosh2k12** [phonegap/build#420]
I am trying to use phonegap build api via PHP. I first tried using the curl to get my apps, which worked great. Code:

```
$config['user'] = "21********h@gmail.com";
$config['password'] = "*******";
$url = "https://build.phonegap.com/api/v1/apps";
$create_method = "remote_repo";
$repo_url = "https://github.com/alunny/phonegap-start.git";
$title = "SampleApp";

$postdata = array(
	"data" => json_encode(array('create_method' => $create_method, 'title' => $title)),
    "repo" => $repo_url
    );
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC); 		
curl_setopt($ch, CURLOPT_USERPWD, $config['user'].':'.$config['password']);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_URL, $url);
$error = curl_error($ch);
$output = curl_exec($ch);
curl_close($ch);
print_r($output);
```

The above code is not working and outputting:
`{"error":"no create_method specified: file or remote_repo"}`

I am not sure why is this happening even though the same method worked for fetching my apps.

**Comment by wildabeast** [comment]
Try this:

    $data = array("create_method" => $create_method, "title" => $title, "repo" => $repo_url);
    $postdata = "data=" . json_encode($data);

If you have a look at the docs, you'll see the sample looks like this:

    curl -u andrew.lunny@nitobi.com -d 'data={"title":"API V1 App","repo":"https://github.com/alunny/phonegap-start.git", "tag":"master", "create_method":"remote_repo"}' https://build.phonegap.com/api/v1/apps

so the post data is 'data=' followed by the json-encoded data (the 'data' field is not json-encoded). also note that your "repo" field is not being json_encoded above.

**Comment by jonhue** [comment]
@wildabeast I've got a similar problem:

```ruby
phonegap = JSON.parse(HTTParty.post("https://build.phonegap.com/api/v1/apps?auth_token=#{phonegap_token}", data: {
    title: 'Example Name',
    create_method: 'remote_repo',
    repo: 'https://github.com/example/repo.git'
}.to_json, headers: { 'Content-Type' => 'application/json' }, format: :plain), symbolize_names: true)
```

returns ...

`{:error=>"no create_method specified: file or remote_repo"}`

**Comment by goya** [comment]
have you tried not using to_json? please post an issue at: https://forums.adobe.com/community/phonegap/build/content so we can troubleshoot.

**Comment by jonhue** [comment]
Here ya go: https://forums.adobe.com/message/9865163

Also: removing `.to_json` could not resolve the issue.

**Comment by jonhue** [comment]
@goya 
Here ya go: https://forums.adobe.com/message/9865163
Also: removing `.to_json` could not resolve the issue.
