### ISSUE TITLE
[Debug] Automatic turn-off 'Debugging' to keep server resources.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#423]
Debug server getting a lot of unnecessary hits when numbers of apps with 'debugging' enabled started simultaneously, without authors realize it is under debug-state running external debugging script. This might cause debug server always running at full capacity at any given time. 

We need to keep server resources so it can be used up efficiently. 

Suggestions:
1- Add an option to enable debugging limited to few hours, days or weeks.
2- Disconnect or turn-off debugging on app/console idle.
3- Others...

Original idea: http://community.phonegap.com/nitobi/topics/debug-not-working-2015#reply_15494308

**Comment by amirudin** [comment]
Related topic: https://console.getsatisfaction.com/nitobi/conversations/debugger-never-working

**Comment by goya** [comment]
added load balancer and placed on ECS.
