### ISSUE TITLE
File size limit on Private Plugin for Paid PGB accounts ?

### ISSUE THREAD

**Issue by youtube-broadcast** [phonegap/build#426]
Hey everyone ,  is it possible if i fork a plugin from github , modify it (remove or add dependencies ) , download it and submit as Private plugin on phonegap build ? It will be 170MB+ file , will this size be allowed ?

**Comment by wildabeast** [comment]
PGB accepts plugins up to a maximum of 50 MB (total files). So I'm afraid at this time that plugin would not be accepted on PhoneGap Build, you'll need to build locally.
