### ISSUE TITLE
[Hydration] Only show 'HI' without loading the actual app.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#428]
Hydration only show 'HI' with dark background without loading the app/pages. This had happen for quite some times and the only workaround is by waiting for a while, kill the app and re-launch. Unfortunately this had become even more frequent lately.

Original topic: http://gsfn.us/t/4n3f9

Related issues:
https://getsatisfaction.com/nitobi/topics/phonegap-hydration-working-not-stable
http://community.phonegap.com/nitobi/topics/hydration-says-hi-and-nothing-else

![hiproblem_inline](https://cloud.githubusercontent.com/assets/995594/7204588/17dd2c94-e556-11e4-96f7-49ebe40fb5e9.png)

**Comment by willbittner** [comment]
I am having the same issue

**Comment by shylor** [comment]
I am having the same issue, but the updater will come up after a bit. However after the update the screen is black.

**Comment by MasodSaidi** [comment]
Having the same issue on both iOS and Android and my testers hate it.

**Comment by shylor** [comment]
I reverted back to an older version of phonegap for now, and it works in that version. I think it is 3.5.

**Comment by wildabeast** [comment]
Can someone share their PGB App ID for an app that is showing this behaviour? Also pls include your Android version.

**Comment by EffEPi** [comment]
I believe this is not a bug.  some people might not to want to rebuild 
their app once that hydration is enabled

-- 
Fabrizio Parrella
-- 
Download gNoclu
Where do you want to go?  I have gNoclu
Founder
Android: https://play.google.com/store/apps/details?id=com.gnoclu.gnoclu
iOS: https://itunes.apple.com/us/app/gnoclu/id909555611?ls=1&mt=8
-- 
WYSKA.net : [W]hat [Y]ou [S]hould [K]now [A]bout
Founder
Web: http://www.wyska.net
Where your Knowledge counts

**Comment by amirudin** [comment]
Reference topic: http://gsfn.us/t/4qvk4

    AppID: 1505451
    Samsung Galaxy S4 @ 5.0.1
    Emulated Nexus 10 @ 5.0.1

Steps to reproduce:
1. Download and run the app with Hydration enabled.
2. Open the app. A grey screen saying 'HI' is displayed and after 5 seconds the hydration interface opens.
3a. Selecting 'Ignore' leads to a black screen and launches hydration on the next start.
3b. Selecting 'Update' updates the app and then displays a black screen.
4. Force quitting the app and then restarting it also results in a black screen.
This problem does not occur when Hydration has been disabled.

**Comment by nweis** [comment]
+1 - This is critical.

**Comment by pbadger** [comment]
+1 This is really frustrating

**Comment by astopo** [comment]
+ 1

**Comment by wildabeast** [comment]
FYI Hydration is not yet supported with phonegap version cli-5.1.1.

**Comment by garmr** [comment]
Same issue on Android 4.1.2, reinstalling/rebuilding the app did not solve this issue.

Right now, I'm no more using Hydration since this functionality is broken for me although delivering updates automatically is critical  to my testers.

**Comment by wildabeast** [comment]
Hydration has been updated to work with Android 5. Use the latest version of PhoneGap to use it:

    <preference name="phonegap-version" value="cli-5.1.1" />

**Comment by MasodSaidi** [comment]
Does this mean that you are still working on a solution for iOS?

**Comment by wildabeast** [comment]
Haven't managed to reproduce said issue on iOS...
