### ISSUE TITLE
IOS Build fails if name does not start with an uppercase letter

### ISSUE THREAD

**Issue by Maistho** [phonegap/build#431]
AppId: [1418007](https://build.phonegap.com/apps/1418007)
If I change the apps name to "Fiskekort", it builds without problem.
This issue only occurs for me if I also include the plugin [cordova sqlite-plugin](https://build.phonegap.com/plugins/2755).

**Comment by brodybits** [comment]
Looks like the same issue also reported in Wizcorp/phonegap-facebook-plugin#830

**Comment by bau720123** [comment]
+1

**Comment by wildabeast** [comment]
this is a bug in the version of plugman we're using. we're currently working on upgrading this, and should be fixed by next week.

fyi the issue / fix https://github.com/apache/cordova-lib/commit/6fd8e23fda5658d5c8d43ecfb6016edb6f713265#diff-8a8fcf987f7dbb1861bdbb1f3d411888R189

**Comment by wildabeast** [comment]
Fixed

**Comment by bau720123** [comment]
thanks @wildabeast 
problem solved...
