### ISSUE TITLE
Phonegap Build with input type=“file” causes app crash on iOS 8.3

### ISSUE THREAD

**Issue by vasanthnataraj** [phonegap/build#435]
Trying to access Camera via HTML5. Phonegap Build with input type=“file” causes app crash on iOS 8.3. It was working fine in iOS 8.2

**Comment by wildabeast** [comment]
Can't reproduce, please provide your App ID which demos the issue.

**Comment by razwasserstein** [comment]
Hi,
We encountered something similar, although not exactly the same.
Our file input was hidden using a css class with (z-index: -1; width:0; height: 0), and it caused a crash.. So we changed it to (opacity: 0) and it seems to have solved the problem. We need to do some more testing to make sure..

Doron Oded,
Remini.me

**Comment by wildabeast** [comment]
Closing due to silence.
