### ISSUE TITLE
Upload failed You uploaded a debuggable APK. - Phonegap-Build

### ISSUE THREAD

**Issue by kwesir** [phonegap/build#436]
![error1](https://cloud.githubusercontent.com/assets/12561130/7911634/b619279a-0857-11e5-916c-b6601de4a75b.png)

Upload failed
You uploaded a debuggable APK. For security reasons you need to disable debugging before it can be published in Google Play. Learn more about debuggable APKs.
You uploaded an APK that was signed in debug mode. You need to sign your APK in release mode. Learn more about signing.
You need to use a different package name because "com.phonegap.www" already exists in Google Play.

**Comment by kwesir** [comment]
Please someone help. It has now been days still can't get answer!

**Comment by goya** [comment]
please start an issue at http://community.phonegap.com/nitobi

**Comment by wildabeast** [comment]
I believe all unsigned builds (which uses a debug key) on PGB will have debugging enabled. If you sign your build (which creates a release build) debugging should be disabled. See the PGB [doc on Android Signing](http://docs.build.phonegap.com/en_US/signing_signing-android.md.html#Android%20Signing).
