### ISSUE TITLE
Incorrect plugin links for NPM plugin when browsing plugins used in app

### ISSUE THREAD

**Issue by yimingkuan** [phonegap/build#437]
https://build.phonegap.com/apps/XXX/plugins

If a plugin installed in a PhoneGap Build app here was sourced from NPM, the plugin link will still reference http://plugins.cordova.io/#/package/[plugin-name] instead of linking the actual NPM package.

**Comment by bau720123** [comment]
+1

**Comment by bau720123** [comment]
hi @yimingkuan 
the problem already solved
press F5 to refresh the page
