### ISSUE TITLE
developing using ASP.Net

### ISSUE THREAD

**Issue by A-BnSultan** [phonegap/build#438]
i'm coding my website using vb.net 
is it possible to upload it to phonegap and create an ios app ?
if it work what database backend should i use best with phonegap ?

thanks

**Comment by wildabeast** [comment]
No, most server side technologies can't run in Phonegap. PhoneGap apps are written in JavaScript (and platform-specific native languages in the context of plugins). Of course any server side APIs that your PG app consumes can be any solution you want.
