### ISSUE TITLE
Build fails on framework tag for android sdk dependency

### ISSUE THREAD

**Issue by floatinghotpot** [phonegap/build#439]
As suggested by google team, the dependency to google play services and android support jar should be defined as framework in plugin.xml. 
```xml
    <!-- android -->
    <platform name="android">
        ....

        <framework src="com.google.android.gms:play-services-ads:+" />
     </platform>
```

It builds pass if using cordova CLI, but it will fail when build with PhoneGap build service, with following error:

```
BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:573: ../../../../../../home/ec2-user/android-sdk/com.google.android.gms:play-services-ads:+ resolve to a path with no project.properties file for project /project
```

Links fyi:
* https://github.com/MobileChromeApps/google-play-services
* https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-identity/issues/3

**Comment by iconico** [comment]
Ok it looks like PhoneGapBuild only supports the &lt;dependency /> mechanism, replacing the &lt;framework /> here to include google-play-services, a cordova-plugin which has been publicly deprecated by its author. 

&lt;dependency id="com.google.playservices" url="https://github.com/MobileChromeApps/google-play-services.git" />

So, why can't I compile &lt;framework src="com.google.android.gms:play-services-location:7.3.0" /> from the Android SDK??

**Comment by goya** [comment]
currently we don't support gradle builds. we are looking to support this soon. i cant give a definite timeline.

**Comment by yimingkuan** [comment]
Fixed: http://phonegap.com/blog/2015/09/28/android-using-gradle/

**Comment by floatinghotpot** [comment]
Great news !
