### ISSUE TITLE
Geolocation Prompt on iOS when Exporting from Construct 2

### ISSUE THREAD

**Issue by donkeyspaceman** [phonegap/build#440]
After building a Construct 2 app with PhoneGap Build, the app will prompt the user with the following message on first run:

"Allow to access your location even when you are not using the app?"

This message will appear despite no geolocation features being active in the Construct 2 project.

This was first reported 5 months ago, where it was believed to be a Construct 2 bug: http://community.phonegap.com/nitobi/topics/how-to-i-turn-off-geolocation-when-using-phonegap-build

I recently reported it to the Construct 2 developer, who believes it is a PhoneGap bug: https://www.scirra.com/forum/touch-object-creates-location-services-prompt-on-ios_t131269

My app update was rejected from the app store because of this prompt. A rapid fix would be appreciated.

**Comment by amirudin** [comment]
+1

Reproducible app: https://github.com/amirudin/c2.git

**Comment by goya** [comment]
construct 2 uses the accelerometer that will trigger this warning

specifically it listens for "devicemotion" and "deviceorientation" events of the window object.

**Comment by AshleyScirra** [comment]
@goya - I am the Construct 2 developer. Why does listening for "devicemotion" and "deviceorientation" prompt a location services request? They don't give the location, only the motion and orientation of the device. Also previous versions of Cordova did not show any prompt, and the PhoneGap CLI does not show any prompt, so it seems to be a problem unique to PhoneGap Build.
