### ISSUE TITLE
Build fails due to minSdkVersion confilicts

### ISSUE THREAD

**Issue by syzgithub** [phonegap/build#443]
When you create a new empty project with phonegap, and build it right after the creation, it will fail. The error message is something like "node_modules/q/q.js:126 throw e;" .  But if you roll back messages further, you will see: 

.../AndroidManifest.xml:15:5 Error:

	uses-sdk:minSdkVersion 7 cannot be smaller than version 10 declared in library /home/stevez/Code/js/lisbon/platforms/android/build/intermediates/exploded-aar/android/CordovaLib/unspecified/debug/AndroidManifest.xml

After playing this for a while, I found that the min SDK version (10) in above file seems hard coded somehow, it is not controlled by the value I set in config.xml. So if I change min SDK version to something greater than or equals 10 in config.xml, the build will success. 

This issue better be fixed.

**Comment by macdonst** [comment]
@syzgithub the update of cordova android makes SDK level 10 the minimum supported version. I suspect your config.xml still has the following line:

```
<preference name="android-minSdkVersion" value="7" />
````

changing it to: 

```
<preference name="android-minSdkVersion" value="10" />
````

should resolve your problem. It is documented at: http://docs.build.phonegap.com/en_US/3.3.0/configuring_preferences.md.html#_android_only

If this resolves your issue please close this ticket.

**Comment by syzgithub** [comment]
Hi Simon,

As I mentioned in my original message, changing minSdkVersion does resolves this issue. But the point is that the generated project without any modification should pass the build. This failure confuses the people especially for the ones first time dealing with PhoneGap. And we better to have just one minSdkVersion setting for a project, right?

Anyway, since you know the problem, I will close the ticket.



Best Regards,

Siyuan Zhu




在 2015-06-18 20:35:51，"Simon MacDonald" <notifications@github.com> 写道：


@syzgithub the update of cordova android makes SDK level 10 the minimum supported version. I suspect your config.xml still has the following line:

<preference name="android-minSdkVersion" value="7" />


changing it to:

<preference name="android-minSdkVersion" value="10" />


should resolve your problem. It is documented at: http://docs.build.phonegap.com/en_US/3.3.0/configuring_preferences.md.html#_android_only

If this resolves your issue please close this ticket.

**Comment by macdonst** [comment]
Agreed but I believe the problem to be a mis-match between the version of cordova android you used to create the project and the one being used to compile it. You probably just need to upgrade your version of cordova to include 4.0.0 or better of the cordova android package and any new project you create will have the correct min sdk version.

If you have an older project you'll need to update your config.xml min sdk version.
