### ISSUE TITLE
App crashes when using input with type="file" on iPad with iOS 8.3

### ISSUE THREAD

**Issue by mlaponder** [phonegap/build#444]
When we create an app which contains a file input, the app crashes when selecting 'Take Photo' or 'Choose Existing' from the popup after clicking the 'Choose File' button.

This can be reproduced by creating an app which contains the following HTML:

```
<form>
    <input type="file">
</form>
```

When we build this app with ponegap.build.com and run this on an iPad with iOS 8.3 the app crashes. Note that when we run this on a iPhone the application does not crash.

When I build the app locally the app doesn't crash and works as expected. The issue is probably related to [https://issues.apache.org/jira/browse/CB-7577](https://issues.apache.org/jira/browse/CB-7577?focusedCommentId=14146483&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14146483,). This is a similar issue, the highlighted comment states that this is resolved when building it with iOS 8 SDK.

**Comment by steve-king** [comment]
+1, I'm having exactly the same problem.

**Comment by asoufi** [comment]
+1, I'm having exactly the same problem.
http://community.phonegap.com/nitobi/topics/file-input-from-phonegap-5-2-0-on-ios9-no-longer-works

Same app built with Phonegap 5.2.0 worked fine on iOS8. After updating to iOS9, it started crashing when you open the "Take Picture" dialog.

**Comment by liuzhen2008** [comment]
+1, crashes with ipad mini 8.4.2

Specifying <preference name="deployment-target" value="8.0" /> did not help.

@asoufi How did you resolve the issue?

**Comment by asoufi** [comment]
Not yet but currently trying with using cordova-plugin-camera plugin:
http://stackoverflow.com/questions/32697975/phonegap-ios9-file-input?sgp=2

Here is additional info FYI:
http://stackoverflow.com/questions/32846039/file-input-from-phonegap-5-2-0-on-ios9-no-longer-works
http://community.phonegap.com/nitobi/topics/file-input-from-phonegap-5-2-0-on-ios9-no-longer-works
https://issues.apache.org/jira/browse/CB-9725?filter=-4

**Comment by ronnyroeller** [comment]
+1

**Comment by jcesarmobile** [comment]
@asoufi, your issue is different, this one is that the app crash when you use input type file on an iPad with iOS 8.4, yours is, input type file doesn't work on any ios 9 device, you should open a new issue for that, I told you it was related to this issue, but they are not the same

**Comment by KristianI** [comment]
+1 ipad iOS 8.0.2, app crashes

**Comment by wildabeast** [comment]
Fixed with Xcode update.

**Comment by TarekJihad** [comment]
1
