### ISSUE TITLE
UNSUPPORTED: Platform element is not supported.

### ISSUE THREAD

**Issue by Deathspike** [phonegap/build#445]
Please add support for the `platform` element. Using `cordova-plugin-splashscreen` as example:

    <platform name="android">
      <preference name="AutoHideSplashScreen" value="false" />
      <preference name="SplashMaintainAspectRatio" value="false" />
      <preference name="SplashScreen" value="splash" />
      <preference name="SplashScreenDelay" value="60000" />
    </platform>
    <platform name="ios">
      <preference name="AutoHideSplashScreen" value="false" />
      <preference name="ShowSplashScreenSpinner" value="false"/>
    </platform>
    <platform name="winphone">
      <preference name="SplashScreen" value="www/splash.png" />
      <preference name="SplashScreenDelay" value="2000" />
    </platform>

As per the documentation for this plugin https://github.com/apache/cordova-plugin-splashscreen#android-quirks, there are several platform-specific quirks that do not play well with each other. The appropriate way to support a scenario like this is using the `platform` element. Since there is no PGB support for this, you would have to stop using PGB and start building locally or alter the `config.xml` and build for each platform one by one.

Migrated from:

http://community.phonegap.com/nitobi/topics/phonegap-build-not-respecting-platform-element

**Comment by amirudin** [comment]
+728

**Comment by jessemonroy650** [comment]
As reported, this appears to be a CLI issue and not a PGB (Phonegap Build) issue.
However the link at the bottom points to a message thread that talks about PGB (and near the end WP8). Apparently, the OP failed to note the real ISSUE.

The real issue is that "WP8 support of the splash screen plugin is pretty bad".

**Comment by Deathspike** [comment]
That's not "the real issue". The real issue that it is impossible to have platform-specific configuration values.  In the example I posted, yes, I illustrated the problem of missing platform-specific configuration values with the splash screen plugin. However, to oblige you, here is an example that cannot be solved by fixing the splash screen plugin:

    <platform name="android">
      <preference name="DisallowOverscroll" value="true" />
    </platform>
    <platform name="ios">
      <preference name="DisallowOverscroll" value="true" />
      <preference name="StatusBarBackgroundColor" value="#000000" />
      <preference name="StatusBarOverlaysWebView" value="false" />
    </platform>
    <platform name="wp8">
      <preference name="Fullscreen" value="true" />
    </platform>

Yes, I use different settings depending on platform concerning plugins and regular settings.

**Comment by aarongusman** [comment]
I support this feature request!

**Comment by jessemonroy650** [comment]
@Deathspike, Thanks for the clarification. +1 on this request.

**Comment by yimingkuan** [comment]
This should be fixed: http://phonegap.com/blog/2015/11/17/config_xml_update/

**Comment by goya** [comment]
this functionality is now available.
