### ISSUE TITLE
phonegap remote build android, fails with "failed to create the zip file"

### ISSUE THREAD

**Issue by breslover** [phonegap/build#447]
This is a fresh installation of Windows 8.1 and the latest npm install phonegap --

http://screencast.com/t/FMrkcsVrZ
http://screencast.com/t/DQt6Hlt7Xx

Thank you

**Comment by wildabeast** [comment]
If you're still experiencing this issue -- its a problem with the cli on the client side, so I'd suggest posting to the [phonegap-cli issue tracker](https://github.com/phonegap/phonegap-cli/issues).
