### ISSUE TITLE
allow-navigation and allow-intent not being copied to compiled config.xml

### ISSUE THREAD

**Issue by wildabeast** [phonegap/build#449]
cordova-plugin-whitelist uses the allow-navigation and allow-intent elements to configure certain behaviours. PGB is not copying these to the compiled config.xml, probably.

**Comment by bau720123** [comment]
I am the repo about this issue
is there any update or ???

**Comment by amirudin** [comment]
Possible related: http://gsfn.us/t/4rz1j

**Comment by wildabeast** [comment]
Deployed.
