### ISSUE TITLE
Can not change default icon

### ISSUE THREAD

**Issue by HKimly** [phonegap/build#450]
i am new phonegap development.I have some problem with changed default icon on build phonegap web site.I try change on config file but it is not work. below is my config file

        <icon src="icon.png" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="ldpi" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="mdpi" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="hdpi" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="xhdpi" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="xxhdpi" />
	<icon src="res/icon.png" gap:platform="android" gap:qualifier="fr-xxhdpi" />

any one could have me ?

(Sorry for my bad English)

Thank in advance

**Comment by goya** [comment]
please start a conversation on community.phonegap.com so we can troubleshoot your issue.
