### ISSUE TITLE
[debug] debug1 produce incomplete js.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#453]
The file below incompletely produced by debug1.build.phonegap.com causing error on weinre session.
http://debug1.build.phonegap.com/target/target-script-min.js

However the same file hosted by debug2 is correct.
http://debug2.build.phonegap.com/target/target-script-min.js

Original topic: http://gsfn.us/t/4rveu

**Comment by goya** [comment]
fixed!

**Comment by svantej** [comment]
Same problem today.
