### ISSUE TITLE
[Build] Slow upload. Page doesn't update infinite loading spinner. App not building

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#454]
Complaint received about slow building, page doesn't update while upload showing infinite loading spinner. In another case the app didn't build at all. This only happen to Free subscriber so far.

Topics:
http://gsfn.us/t/4s8qc
http://gsfn.us/t/4s8sq

**Comment by wildabeast** [comment]
We had a misconfiguration with our web servers for a time that was causing a lot of requests to fail. All fixed now.
