### ISSUE TITLE
CrossWalk Engine build preferences to be ARM / x86 compatible

### ISSUE THREAD

**Issue by FlossyWeb** [phonegap/build#455]
Hi there,

I saw in this topic (https://crosswalk-project.org/documen...) from the crosswalk project FAQ/Documentation that it is possible to include both ARM and x86 compatible engines in a single build or to upload to Google Play two different packages.

So it looks like we just need some crosswalk preferences to configure in config.xml file to properly use this plugin and BE ARM AND X86 DEVICE FRIENDLY !

Can someone help here ?

**Comment by jessemonroy650** [comment]
@FlossyWeb
your link did NOT show up, can you please update that.
TIA
Jesse

**Comment by FlossyWeb** [comment]
@jessemonroy650 
[link to Crosswalk documentation FAQ](https://crosswalk-project.org/documentation/about/faq.html#Distributing-Crosswalk-Project-applications)
Scrolling down a little bit, you may particularly take a look at the "How can I distribute a Crosswalk Android application across multiple architectures?" sub-topic.
Thank you Jesse, any help is really appreciated here.
François.

**Comment by amirudin** [comment]
+1

**Comment by wildabeast** [comment]
@FlossyWeb I've uploaded an x86 version of the plugin to PGB: https://build.phonegap.com/plugins/4652

Try it out and let me know if it does the trick:

    <gap:plugin name="org.crosswalk.engine.x86" version="1.3.0" source="pgb" />

**Comment by FlossyWeb** [comment]
@wildabeast Thanks dude it surely does the trick !
Do you think this PGB plugin will be updated in the same time the other plugin  (<gap:plugin name="org.crosswalk.engine" version="1.3.0" source="pgb" />) will be ?
It's such a huge needle you've just got out of my foot, I owe you big time Ryan thanks again ;-)

**Comment by wildabeast** [comment]
yes for the time being if there's any updates that need to occur on the arm version, we'll replicate them on the x86 version. hopefully we're not too far away from being able to build the npm version of the crosswalk plugin (currently fails on build due to gradle requirements), at which point we'll likely end support for the PGB hosted version in favour of that one.

**Comment by whitecolor** [comment]
Hey guys I have a question:

How to build crosswalk for ARM and x86 (separately) 
currently I have preference 
```XML
<preference name='xwalkCommandLine' value='--disable-pull-to-refresh-effect'>
```

and plugin for `android` platform 
```XML
<plugin name='cordova-plugin-crosswalk-webview-pgb-adapt' version='1.4.0-dev-5'>
```

It seem to work well on x86 device, but crushes on ARM device. I know that there should be different builds for both archs, so my questings are 

1) How to get separate build for ARM (it seem that x86 is by default)? 
2) How to get combined build (that contain both versions)?

**Comment by bau720123** [comment]
+1

**Comment by kbalaguru** [comment]
How to build crosswalk for ARM and x86 (separately) 

I'm using cordova-plugin-crosswalk-webview in my config.xml like below. 

`<plugin name="cordova-plugin-crosswalk-webview"/> `

But it seems that PhoneGap Build outputs only the .x86 APK. 
With certificate it give x86 build. Without certificate it gives ARM version. 

Any idea how we can get the 64bit APK (arm) in release version?

**Comment by FlossyWeb** [comment]
@kbalaguru well I build with pgb still using : 
<gap:plugin name="org.crosswalk.engine.x86" version="1.3.0" source="pgb" />
Or
<gap:plugin name="org.crosswalk.engine" version="1.3.0" source="pgb" />
Respectively for x86 or arm devices, it works well in release for both.
I say Or not And because first you build the arm version with one plugin then the x86 version with the other plugin ;-)

**Comment by benmcmaster** [comment]
Is there a way to use the newest crosswalk plugin on npm?

<plugin name="cordova-plugin-crosswalk-webview" source="npm" version="1.7.0" />

It seems like the PGB plugin is pretty far behind... But we still have the problem that @kbalaguru mentioned above. We need to be able to build two APKs evidently. It is kinda weird that when build is unsigned it builds the arm version, but when it's signed it builds the x86 version.

@wildabeast what is the status on building from the npm version of the plugin?

Issue on PhonegapBuild forum: https://forums.adobe.com/thread/2150271

**Comment by benmcmaster** [comment]
Looks like this dude just solved the problem...
https://github.com/MBuchalik/cordova-build-architecture
