### ISSUE TITLE
[iOS9] Blackbar on top and bottom

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#456]
Several users report app displaying blackbar on top and bottom after iOS9 upgrade.

Original topic: http://gsfn.us/t/4scif

**Comment by AmsterdamInc** [comment]
Perhaps correlated to scaling issue, since upgrading to iOS 9?

![ios_9_phonegap_scaling_issue](https://cloud.githubusercontent.com/assets/14772265/10018792/c2a81c2e-6139-11e5-91ec-35746ad4e8c5.jpg)

**Comment by wildabeast** [comment]
Responded on GS thread linked above.

Issue appears to be that on iOS 9, if you had www/ at the start of the path to your splash screen, that will no longer resolve and will break your splash and add the black bars. i.e. change:

    <gap:splash gap:platform="ios" height="960" src="www/res/screen/ios/screen-iphone-portrait-2x.png" width="640" />

to 

    <gap:splash gap:platform="ios" height="960" src="res/screen/ios/screen-iphone-portrait-2x.png" width="640" />

**Comment by nikken1** [comment]
Thank you for this. It solves my issue

**Comment by EngHell** [comment]
I have this issues while having the src attribute pointing to "res/.../screen-iphone-portrait-2x.png"
