### ISSUE TITLE
Upload sucks!

### ISSUE THREAD

**Issue by snigglet** [phonegap/build#458]
In uploading a large ZIP (~400MB) this environment is terrible. When you begin the ZIP upload you have no ability to know where you are. If it fails, you don't know why. This HAS to be improved.
Is there an alternative to the WEB upload to get this into the Adobe Build CDN. Once it is up, it works great. But this is terrible @ moment.

**Comment by wildabeast** [comment]
Uploading files this large in a browser is going to be inconsistent in most environments.

[Try using the API from a command line instead](http://docs.build.phonegap.com/en_US/developer_api_write.md.html#_post_https_build_phonegap_com_api_v1_apps).

**Comment by snigglet** [comment]
I agree that is inconsistent but I was testing things. It would be good to have an indicator of some sort - it goes into a black box. You have no way of knowing.

Instead I now pull from github - that is very nice. Will check the API you list.

Thanks for getting in touch.
Jean

**Comment by wildabeast** [comment]
Closing for now then if you've solved your issue. Will make note to improve the user feedback in the upload UI.

**Comment by snigglet** [comment]
Great - thanks

On Fri, Oct 2, 2015 at 1:55 PM, Ryan W <notifications@github.com> wrote:

> Closing for now then if you've solved your issue. Will make note to
> improve the user feedback in the upload UI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/build/issues/458#issuecomment-145152925>.
>



-- 
Jean Holt
CEO, Gatelets
415.999.2789
gatelets.com
