### ISSUE TITLE
Unable to generate android build with Phonegap build using cli-5.2.0 but works fine with 3.7.0 phonegap version

### ISSUE THREAD

**Issue by sumitebizon** [phonegap/build#459]
Hi Support 

We are unable to generate android build with Phonegap build using cli-5.2.0 but it works fine with 3.7.0 phonegap version can you please check the issue and help us to resolve it.

Attaching the Log ERROR
BUILD FAILED
/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 10 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: release,-f,/project/build.xml

Thanks
Mofluid team

**Comment by yimingkuan** [comment]
Ensure you've followed all the steps here: http://community.phonegap.com/nitobi/topics/notes-for-upgrading-to-cli-5-1-1-on-pgb

**Comment by wildabeast** [comment]
@sumitebizon if this is still a problem use the link provided by @yimingkuan, or share your App ID here and we'll have a look. Will close if we don't see a response.
