### ISSUE TITLE
Installed NPM plugin versions not shown on PGB app page

### ISSUE THREAD

**Issue by yimingkuan** [phonegap/build#460]
On https://build.phonegap.com/apps/[APP_ID]/plugins, unless a version is specified, the NPM plugin version installed in the app is left empty.

**Comment by wildabeast** [comment]
Unfortunately at this time the plugin version that npm on our build servers installs isn't returned to our DB. Realistically we probably won't be adding this. If plugin version is a concern, users should go to the plugin's npmjs.com page and explicitly lock to a version.

Closing as won't fix.

**Comment by goya** [comment]
reopening this!

**Comment by goya** [comment]
done.  we have been storing the plugin.json manifest for the project so we can actually get this info.
