### ISSUE TITLE
[Build] Gradle build add additional digit '8' after versionCode

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#462]
Gradle build add number '8' after every versionCode similar to this:
https://issues.apache.org/jira/browse/CB-8976

Topic: https://getsatisfaction.com/nitobi/topics/android-versioncode-is-changed-by-gradle

**Comment by jskrepnek** [comment]
+1

any known work arounds?

**Comment by bau720123** [comment]
+1

**Comment by bmjjohn** [comment]
+1

**Comment by wildabeast** [comment]
The android-versionCode preference should now override the one messed with by gradle. Use this:

    <preference name="android-versionCode" value="1234" />

**Comment by jskrepnek** [comment]
Is that live on Build now @wildabeast?

**Comment by wildabeast** [comment]
@jskrepnek its live yes

**Comment by hungdoan2** [comment]
@wildabeast  Is it working?, I have just tried, but I seem not working.

**Comment by hungdoan2** [comment]
I follow this tutorial to extend `cdvVersionCode`. It works perfectly
https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#extending-build-gradle

**Comment by prantikv** [comment]
@hung-doan can you provide the script that you used to copy the file before build
