### ISSUE TITLE
ERROR ITMS- 90035 invalid signature

### ISSUE THREAD

**Issue by 28ashwin** [phonegap/build#463]
ERROR ITMS- 90035 invalid signature

Hi All, 
I am trying to upload ipa on apple store but it’s giving me “ERROR ITMS- 90035 invalid signature” error. 
I have followed below process. 
The first step in setting up a distribution profile is to create a certificate signing request. You can do this on your Mac. Launch the Keychain Access.app that is stored in Applications/Utilities. Then execute the following steps in yourKeychain Access application: 
1. Select Preferences > Certificates and ensure that Online Certificates Status 
Protocol (OSCP) and Certificate Revocation List (CRL) are set to Off. 
2. Select Keychain Access > Certificate Assistant > Request a Certificate From a 
Certificate Authority... and ensure that you do not have any of your certificates 
highlighted, otherwise the Provisioning Portal will not accept your certificate request. 
3. Enter your valid e-mail address in the User Email Address field. Ensure that the e-mail 
address is the same as the one you used when you registered as an iOS Developer. 
4. Enter your name in the Common Name field. Ensure that the name you enter is the 
same as the one you used when you registered as an iOS Developer. 
5. A CA Email Address is not required. 
6. Select the Save to disk radio button and tick Let me specify key pair information, 
if it is present. 
7. Press Continue. 
8. A dialog appears that allows you to specify where you would like the certificate signing 
request to be stored. Specify a location and select Save. 
9. Press Continue. 
10. The certificate is then generated and written to the file you specified under step 8. 
After you have generated a certificate signing request, you need to submit your certificate for approval. Log into the iOS Provisioning Portal that is accessible from:https://developer.apple.com/ac....... 
This link takes you directly to the Certificates, Identifiers & Profiles section of your iOs developer account. Select the "Production" tab and follow these steps: 
1. Select the Add Certificate button. 
2. Select "App Store and Ad Hoc" as type then press continue 
3. On next screen press "Continue" 
4. On next screen select "Choose File" and select the certificate you created in previous step and then press "Generate" 
Remain on the same page as the one you were on when you submitted the certificate signing request, then follow these steps to download and install the certificate: 
5. Download Generated certificate by clicking the "Download" button. 
6. Double click the downloaded certificate to install (alternatively drag to the keychain utility) 
It is important that you backup the keys you created. This allows you to develop on multiple Macs or reinstall the keys after unexpected data loss. You can export your private keys and certificates through the Keychain Access application: 
1. Open the application Keychain Access.app that is stored in Applications/Utilities. 
2. Select Keys. 
3. Highlight the private key associated with the distribution certificate. 
4. Select File > Export Items. 
5. A window opens that allows you to specify where you would like to save your certificate. 
6. Select Personal Information Exchange (.p12) as file format. 
7. Select the file name. 
8. Select Save. 
9. You are prompted for passwords that allow you to access the key in the future 
This is the final stage and will create the distribution provisioning profile you need to use when building your iOS standalone. Start by selecting the "Distribution" tab from "Provisioning Profiles"- 
1. Select New Profile (+) 
2. Select App Store as the Distribution Method. 
3. Enter the Profile name. 
4. Ensure that your Distribution Certificate has been created and is displayed correctly. 
5. Select the appropriate App ID for your applicatoin 
6. Select Generate. 
7. Select the Download button from next to the Distribution Provisioning Profile you created. 
This allows you to download the .mobileprovision file. 
8. Double click the .mobileprovision install the Distribution Provisioning Profile on your computer.

This is the process I am using to generate ipa. Then I want to upload this ipa with application loader , But it’s giving me signing code error. Please see attached screenshot .

Please help.

![untitled 1](https://cloud.githubusercontent.com/assets/14816673/10452541/800c77a8-715a-11e5-810b-710f19169d3c.png)

**Comment by goya** [comment]
closing this out.
