### ISSUE TITLE
Order of `preference` tags in generated `config.xml` is wrong

### ISSUE THREAD

**Issue by matthewgertner** [phonegap/build#465]
I am using `cordova-plugin-statusbar` to customize the appearance of my app's statusbar on iOS. Specifically, I want to change the value of `StatusBarOverlaysWebView` to false, so I include the following line in my `config.xml`:

```
<preference name="StatusBarOverlaysWebView" value="false" />
```

This works great when I test using a local XCode build. When I build on PhoneGap Build, however, the default setting for this value (which is `true`) is not overridden.

After considerable head-scratching, I noticed that the order of the preferences in `config.xml` is different in the one generated by PhoneGap. In my local build, the following lines from the plugin's `plugin.xml` are included _before_ the line overriding the setting:

```
    <feature name="StatusBar">
        <param name="ios-package" value="CDVStatusBar" />
        <param name="onload" value="true" />
    </feature>
    <preference name="StatusBarOverlaysWebView" value="true" />
```

In the `config.xml` generated by PhoneGap, however, these lines appear at the very end of the file. I am guessing that "last write wins" and thus the default value is overwriting my custom preference.

Is there some way for me to influence this or is it just a PhoneGap Build bug?

**Comment by goya** [comment]
fixed on Nov 13, 2015
