### ISSUE TITLE
<input type="file"> does not launch a camera option in android 5 +

### ISSUE THREAD

**Issue by liuzhen2008** [phonegap/build#466]
Does that mean we are forced to use the camera plugin for all the file input? Or is there some kind of configuration I can do to solve this issue?

**Comment by jcesarmobile** [comment]
input file never launched the camera on android on previous android versions

**Comment by liuzhen2008** [comment]
@jcesarmobile  Yes you are right! There appears to be an open bug in cordova that addresses this issue.
