### ISSUE TITLE
[Build] cli-5.2.0 cause app cannot install on iOS

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#468]
cli-5.2.0 build causing app cannot install on iOS (7, 8 and 9) with error message: 
"A signed resource has been added, modified, or deleted"

Something in common:
Node @ ios.136 (mh1-ewr-f31.local) [72937]
Node @ ios.132 (1055193132.local) [21457]

Original topics:
http://gsfn.us/t/4sgv7
http://gsfn.us/t/4snfx

**Comment by wildabeast** [comment]
Both the original topics seem to be solved, re @goya's fix.
