### ISSUE TITLE
Bad link on plugins site

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/build#469]
On https://build.phonegap.com/plugins there is a banner

The PhoneGap Build Plugins Repository is slowly being deprecated in favour of Cordova plugins on npm.

It has a link to http://plugins.cordova.io/npm/index.html, but it no longer exists, it should be just http://plugins.cordova.io/ or http://cordova.apache.org/plugins/

**Comment by amirudin** [comment]
+1

**Comment by jessemonroy650** [comment]
+1

**Comment by goya** [comment]
fixed.
