### ISSUE TITLE
input type file doesn't work on iOS 9

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/build#470]
This was opened on the cordova JIRA, but it doesn't affect cordova, just phonegap build, so I open it here

Original text
In iOS 9 when a input with type file is tapped only appears a non-clickable "Cancel" button in the context menu and never goes away.

https://issues.apache.org/jira/browse/CB-9688

**Comment by jessemonroy650** [comment]
is this related? 
File Input from PhoneGap 5.2.0 on iOS9 - No longer works
https://issues.apache.org/jira/browse/CB-9725

**Comment by jcesarmobile** [comment]
Same issue, I closed it as duplicate. He was using phonegap build too.

**Comment by asoufi** [comment]
Thanks for your help. I created a simple example and uploaded it to Build.Phonegap.Com:
https://build.phonegap.com/apps/1718718/share (app id: 1718718)

- When installed on iPhone 5s with iOS9, the file input dialog only shows "cancel" and the app crashes
- Same app works OK on iPhone 5s with iOS8
- Same index.html page works fine when viewed in Chrome/Safari on same iPhone 5s with iOS9.

I look forward to your reply.

**Comment by scottopolis** [comment]
I'm also seeing this issue. The bug does not appear to be fixed by using the latest version of Phonegap Build, which is cli-5.2.0 right now.

**Comment by yarcub** [comment]
From https://issues.apache.org/jira/browse/CB-9688 it's not reproducible on cordova cli 5.3.3. Is there any estimate on supporting a [phonegap cli release](https://github.com/phonegap/phonegap-cli/releases) that includes the cordova cli 5.3.3 (e.g. phonegap cli ~5.3.5)?

**Comment by wildabeast** [comment]
This issue is fixed with the recent upgrade to XCode 7. Please rebuild and test.

**Comment by asoufi** [comment]
Thank you for the fix/update. I will rebuild using build.phonegap.com and confirm.

**Comment by scottopolis** [comment]
@wildabeast Thanks for the update, but for me this is an issue with Phonegap Build. I use Xcode 7.1 for my local builds, but that wouldn't pertain to building using Phonegap Build.

**Comment by jcesarmobile** [comment]
they updated the xcode they use to compile on phonegap build!
I confirm the bug is fixed and https://github.com/phonegap/build/issues/444 is fixed too

**Comment by wildabeast** [comment]
@scottopolis PGB uses Xcode as well -- and PGB has updated to XCode 7.1.

**Comment by jessemonroy650** [comment]
Thanks for the note. I'll add that.
