### ISSUE TITLE
[Docs] October 15th passed, plugin.cordova.io still can be used.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#474]
October 15th passed, plugin.cordova.io still can be used. Should we adjust the docs, display additional message or get rid of the source entirely? Any ETA?

Original topic: http://gsfn.us/t/4sqzz

**Comment by wildabeast** [comment]
plugins.cordova.io is now disabled, and the docs have been updated. will get it out on twitter as well. thanks @amirudin
