### ISSUE TITLE
PGB ignores android-minSdkVersion / android-targetSdkVersion preferences

### ISSUE THREAD

**Issue by yimingkuan** [phonegap/build#476]
As per topic:

Links on GetSat:
https://getsatisfaction.com/nitobi/topics/android-targetsdkversion-doesnt-have-any-influence-on-generated-apk
https://getsatisfaction.com/nitobi/topics/application-not-installed

**Comment by wildabeast** [comment]
Appears resolved based on those threads.

**Comment by gustavocampos** [comment]
I moved from phonegap-cli 5.2.0 to 6.1.0 and now I'm having this same problem, I used to build the same app (1719656) twice, one for min sdk = 15 and max sdk = 19, and another one for min sdk = 21 and target sdk = 23, now every app I build comes with min sdk 15+ and play store doesn't accept both APKs like that.

Is it possible to reopen this issue?
