### ISSUE TITLE
iOS fails to find existing plugin on NPM

### ISSUE THREAD

**Issue by yimingkuan** [phonegap/build#477]
Related topic: https://getsatisfaction.com/nitobi/topics/-only-ios-error-the-following-plugin-or-plugin-version-is-not-on-npm-de-appplant-cordova-plugin-badge-0

User attempts to install the NPM plugin de.appplant.cordova.plugin.badge@0.7.1 from npm, but the build logs report that no such plugin exists. The plugin is visible here though: http://cordova.apache.org/plugins/?q=de.appplant.cordova.plugin.badge

**Comment by goya** [comment]
this plugin has an iOS dependancy of de.appplant.cordova.common.registerusernotificationsettings, which is not on npm.  please follow up with plugin author.
