### ISSUE TITLE
File type=input not working on iOS 9

### ISSUE THREAD

**Issue by tanjentman** [phonegap/build#478]
The latest Phonegap Build is doing something that is causing the file=type input to not work on iOS 9.  It works fine on iOS 8.

**Comment by jcesarmobile** [comment]
duplicate of https://github.com/phonegap/build/issues/470

BTW, test on an ipad on iOS 8 and you'll realize that it didn't work either.

**Comment by wildabeast** [comment]
Closed as duplicate. Original issue #470 now fixed.
