### ISSUE TITLE
Please please support custom URL schemes for Android too :)

### ISSUE THREAD

**Issue by yoav-zibin** [phonegap/build#479]
Hi,
This doc says:
http://docs.build.phonegap.com/en_US/configuring_custom_urls.md.html#Custom%20URL%20Schemes
iOS allows registration of
custom URL Schemes.
Is it only relevant for iOS?

I would love to have a custom URL scheme for my app, e.g., so you could launch it with:
tictactoe://

I tried 3rd party plugins:
https://github.com/Telerik-Verified-Plugins/Custom-URL-scheme
https://github.com/EddyVerbruggen/Custom-URL-scheme
but they don't work (and crashed the app once).

If it doesn't work for Android, can you at least point in the documentation to a plugin that work on Android?

**Comment by yoav-zibin** [comment]
Also, the page has a link to Apple page:
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007072-CH7-SW50
which has nothing to do with Custom URL schemes :)

So I have no idea what the "role" means:
role: must be Editor, Viewer, Shell or None, optional, defaults to None.

I've read other tutorials (http://code.tutsplus.com/tutorials/ios-sdk-working-with-url-schemes--mobile-6629), but they don't mention a role.

**Comment by yoav-zibin** [comment]
Ok, solved it!
But it would be nice if you improve the documentation: explain how to do it on Android, and what is the mysterious "role" on iOS :)


A) Added the namespace (ns):
       xmlns:android   = "http://schemas.android.com/apk/res/android"
B) Added this:


    <gap:config-file platform="android" parent="/manifest/application" mode="add" >
      <activity android:name="com.gamingplatform.tictactoe.TicTacToe" android:label="Tic Tac Toe">
        <intent-filter>
          <action android:name="android.intent.action.VIEW"/>
          <category android:name="android.intent.category.DEFAULT"/>
          <category android:name="android.intent.category.BROWSABLE"/>
          <data android:scheme="tictactoe"/>
        </intent-filter>
      </activity>
    </gap:config-file>
    <gap:url-scheme role="None">
      <scheme>tictactoe</scheme>
    </gap:url-scheme>

**Comment by jessemonroy650** [comment]
Can someone close this? The OP says solved in 3rd message.
