### ISSUE TITLE
Cordova Fixed-PGB NOT:  Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by Farufon** [phonegap/build#489]
Any word on when PhoneGap build service will fix the Push Notification issue?

Rather than "Living with the Notification" as PGB suggests, it would be nice not to and be able to build apps like in Cordova without this problem.  Cordova fixed it a year.5 ago.

Our config.xml has nothing stating push notifications, but Apple seems to think we do, when submitting and issues this warning. 

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

**Comment by goya** [comment]
see #485 

this issue closed as duplicate.
