### ISSUE TITLE
Phonegap Build documentation out of date

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/build#492]
[Platform Build Selection](http://docs.build.phonegap.com/en_US/configuring_basics.md.html#_platform_build_selection) has changed with the recent change to "<platform>".

It reads: *By default PhoneGap Build builds your application for every platform.*

*It should read:** By default, PhoneGap Build builds your application for *Android* and *iOS*.

**Comment by goya** [comment]
if no platform is specified then all platforms are built. we still build for wp8.

why would we replace it with only android and ios? am i missing something?

**Comment by jessemonroy650** [comment]
@goya, 
This has not been the case since  [config.xml gets an update - part 2 !!!!!!|(http://phonegap.com/blog/2015/11/19/config_xml_changes_part_two) - 19 Nov 2015. 

Volunteers (Petra and myself) assumed it was another undocumented change. We have been advising people to add `<platform name="winphone" />`, if they want a windows build.

Here is the [one such report](http://community.phonegap.com/nitobi/topics/windows-phone-dont-appear-to-build). I can fine more, if need be.

Jesse

**Comment by goya** [comment]
do you have an app id or config.xml to replicate?

**Comment by jessemonroy650** [comment]
Hmmmm.... mine builds. I've seen it fail before, and I've seem it fail for people. No explanation. 
It may be that people have old builds configurations, they have made minor updates to. 

IT NOW BUILDS AS IS DOCUMENTED. Okay. Close this.

Source: https://github.com/jessemonroy650/Phonegap--Generic-Boilerplate8
Build: https://build.phonegap.com/apps/1882622/share (will remove in a few days.)
