### ISSUE TITLE
I am Developing cross plotform application using Phonegap/cordova .In that i am using html5 video tag and it is played in upto jellybean android version, but in kitkat and lollipop i am getting audio but video is not visible .So how to resolve it

### ISSUE THREAD

**Issue by nagaraju7752** [phonegap/build#493]
Please provide solution

**Comment by wildabeast** [comment]
what version of phonegap are you using? and are you using PhoneGap Build?

**Comment by nagaraju7752** [comment]
cordova version  :5.4.1

**Comment by nagaraju7752** [comment]
it is development stage only i am not using phonegap build

**Comment by nagaraju7752** [comment]
please provide solution as early as possible.

**Comment by goya** [comment]
this is an issue tracker for PhoneGap Build not cordova or PhoneGap.  Please ask a question on the google group https://groups.google.com/forum/#!forum/phonegap
