### ISSUE TITLE
Missing entire section for 'Events' and 'deviceready'

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/build#494]
No where on the Phonegap Build website is there a page for "Events".
The most important part being 'deviceready', which newbies miss on a regular basis.
My only alternative is to turn them to the Cordova website, which confuses them further.

Jesse

**Comment by wildabeast** [comment]
PhoneGap Build intentionally doesn't re-document the Cordova API's, since they're constantly changing with releases, are plugin based and distributed. That said perhaps we could make this fact more clear in our documentation. Will review.

**Comment by jessemonroy650** [comment]
@wildabeast Anything to help reduce the confusion will help. Even a page that tells people to go to Cordova would work. TIA Jesse
