### ISSUE TITLE
Zip file issues

### ISSUE THREAD

**Issue by czb** [phonegap/build#495]
When I upload the following file: [dist.zip](https://github.com/phonegap/build/files/117195/dist.zip), sometimes I get `no index.html present`, sometimes it works. Even when I get no error and it compiles, all the files in all subfolders under the www folder are empty in the resulting IPA file, see: [Brosyn.zip](https://github.com/phonegap/build/files/117198/Brosyn.zip). I have zipped the files using `gulp-zip`.

**Comment by benjasHu** [comment]
+1

**Comment by goya** [comment]
your zip is craaaaazy.  bad folder permissions. what platform was this zipped in?

it's probably related to this https://github.com/sindresorhus/gulp-zip/issues/62

**Comment by softwaredude** [comment]
See https://github.com/sindresorhus/gulp-zip/issues/64#issuecomment-191659258.  Using the `{nodir: true}` option to `gulp.src` with gulp-zip was a simple and effective solution to the upload problems I was experiencing.
