### ISSUE TITLE
For Config.xml missing documentation for elements field 'author' and 'name'

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/build#497]
Recently, with cli-6.0.0 there were several failures that point to items that need to be documented in the
Docs -> The Basic -> [Essentials](http://docs.build.phonegap.com/en_US/configuring_basics.md.html#_essential_properties)

The following message thread has the highlights.
[CONFIRMED: PGB fails with cli-6.0.0 for winphone](http://community.phonegap.com/nitobi/topics/confirmed-pgb-fails-with-cli-6-0-0-for-winphone)

The following needs to be added.

1) a dash (-) is not allowed in the `<name>` field for Windows, but not Android and iOS
2) the `<author>` element is required for Windows, but not Android and iOS
3) the `<author>` is listed in the example, but not describe in the documentation

TEST CODE: https://github.com/jessemonroy650/try-version6
TEST BUILD: https://build.phonegap.com/apps/1911783/builds

Jesse

**Comment by tonijn** [comment]
The Phonegap Documentation [has its own repo](https://github.com/phonegap/phonegap-docs)

**Comment by jessemonroy650** [comment]
Thanks. Refiled here: https://github.com/phonegap/phonegap-docs/issues/206
