### ISSUE TITLE
iOS build with cli-6.0.0 fails due to plugins

### ISSUE THREAD

**Issue by czb** [phonegap/build#498]
When I build IOS with `<preference name="phonegap-version" value="cli-6.0.0" />`, the build fails. With `<preference name='phonegap-version' value='cli-5.2.0' />` the build succeeds.

It fails when compiling plugins. See

```
#import <Cordova/NSData+Base64.h>
        ^
1 error generated.
```

Here is the [build log](https://github.com/phonegap/build/files/133985/fail.txt).

These plugins I use:

    <gap:plugin name="io.litehelpers.cordova.sqlite" />
    <gap:plugin name="org.apache.cordova.splashscreen" />
    <gap:plugin name="org.apache.cordova.geolocation" />
    <gap:plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" />
    <gap:plugin name="org.apache.cordova.file" />
    <gap:plugin name="cordova-plugin-inappbrowser" source="npm" />

Right now, you can see the compilation issue here:

https://build.phonegap.com/apps/1896098/builds

**Comment by goya** [comment]
what app id is it? also be aware not all plugins work with every version of cordova.

**Comment by czb** [comment]
The app id is 1896098

**Comment by goya** [comment]
cool, yeah i was on my phone and didnt see the whole post with the link to your app!

basically not all plugins are compatible with all versions of cordova. and the plugin authors dont specify the compatibly explicitly, so hard to work out the full list of compatibile plugins.

please update your plugins to the latest plugins on npm and it should be ok.  be sure to use the <plugin /> element not the <gap:plugin /> element.
