### ISSUE TITLE
Collaborator docs missing (exists on outdated website)

### ISSUE THREAD

**Issue by shazron** [phonegap/build#499]
The only reference I could find is:
http://docs.phonegap.com/en/edge/guide_phonegap-build_test_index.md.html

Which tells us its outdated and to go to:
http://docs.phonegap.com/

... which AFAIK doesn't contain any Build docs.

The current PhoneGap Build docs are also missing Collaborator feature docs:
http://docs.build.phonegap.com/

![screen shot 2016-02-24 at 9 15 18 am](https://cloud.githubusercontent.com/assets/36107/13294676/f4893d94-dad9-11e5-889d-e7f8ce5b3ac2.png)

**Comment by wildabeast** [comment]
http://docs.build.phonegap.com/en_US/tools_collaboration_and_sharing.md.html#Collaboration%20and%20Sharing
