### ISSUE TITLE
SSL Vulnerability and Jetty HttpClient

### ISSUE THREAD

**Issue by EMart002** [phonegap/build#501]
I cannot connect to PhoneGap Build Service via Jetty HttpClient V 9.3.7.v20160115.
It seams, that they have made some major changes due to some ssl vulnerability. *)

Could you phonegap devs pls check this and try to establish a connection with jetty to your server? If help needed, pls let me know.

Btw in the former version of jetty (V9.2.x), everything worked fine. Since they have updated they sourcecode recently due to those vulnerability issues, i was thinking to let you know.

*) http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/commit/jetty-util/src/main/java/org/eclipse/jetty/util/ssl?h=jetty-9.3.x&id=0a1b0b2bc69ea7e7f5f44992f47a84f926cdeebb

**Comment by EMart002** [comment]
This is my unit-test btw:

```
SslContextFactory sslContextFactory = new SslContextFactory();
sslContextFactory.setTrustAll(true);
        
HttpClient httpClient = new HttpClient(sslContextFactory);
httpClient.setExecutor(Executors.newCachedThreadPool());
httpClient.setMaxConnectionsPerDestination(256);
httpClient.setMaxRequestsQueuedPerDestination(256);
httpClient.setRequestBufferSize(10000);
httpClient.setResponseBufferSize(10000);
httpClient.setMaxRedirects(5);
httpClient.start();

Request request = httpClient.newRequest(new URI("https://build.phonegap.com/api/v1/apps"));
request.getHeaders().add("Authorization", "Basic " + Base64.encode(String.valueOf({user-name} + ":" + {password}).getBytes()));

final FutureResponseListener listener = new FutureResponseListener(request, 2 * 1024 * 1024);
request.send(listener);
try {
    final ContentResponse response = listener.get();
    int statusCode = listener.getStatus();
    if (statusCode == 0) {
        //no connection to host
    } else if (isStatusCodeOk(statusCode)) {
        //parse response and do something
    }
} catch (InterruptedException | ExecutionException e) {
    listener.cancel(true);
}
```

**Comment by goya** [comment]
try now.

**Comment by EMart002** [comment]
Works great! Thy! But what caused the problem?

**Comment by goya** [comment]
i updated the accepted cipher list on the servers.
