### ISSUE TITLE
Why now? Error about malformed config.xml

### ISSUE THREAD

**Issue by Farufon** [phonegap/build#502]
@andersborgabiro   My last build was 23 days ago. Worked great as it has been for months before. 

Now, I go back to PGB, and Update my code, FROM THE SAME FILES and I get an "Unable to create app: mallformed config.xml" error. Nothing changed. Identical files. XML validator checks.   Has something changed on the server side in 23 days that will now reject the same file that worked before?

It should be noted that the config.xml file is still placed in the root directory, above the www directory.  This has always worked. 

It appears the requirements for PGB have changed in the last couple weeks. 

Here's config.xml that has not changed and working for months until today.  

    <?xml version='1.0' encoding='utf-8'?>
    <widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="com.app.stuff" version="1.3.3">
    <name>Hexio for Artists</name>
    <description>Tool Usage</description>
    <author href="http://domain.com" email="support@domain.com">Development Team</author>
    <content src="index.html"/>
  
    <preference name="permissions" value="none"/>
    <preference name="orientation" value="default"/>
    <preference name="target-device" value="universal"/>
    <preference name="fullscreen" value="true"/>
    <preference name="webviewbounce" value="true"/>
    <preference name="prerendered-icon" value="true"/>
    <preference name="stay-in-webview" value="false"/>
    <preference name="ios-statusbarstyle" value="black-opaque"/>
    <preference name="detect-data-types" value="true"/>
    <preference name="exit-on-suspend" value="false"/> 
    <preference name="disable-cursor" value="false"/>
    <preference name="android-minSdkVersion" value="14"/>
    <preference name="android-installLocation" value="auto"/>
    <preference name="disable-push-notifications" value="1" />
  
    
    <preference name="phonegap-version" value="cli-6.0.0" />
  
    
    <preference name="disable-push-notifications" value="1" />
  
    
    <preference name="SplashScreenDelay" value="4000" />
    

    <preference name="show-splash-screen-spinner" value="false" />
    <preference name="FadeSplashScreenDuration" value="2000" />
    <preference name="FadeSplashScreen" value="true" />
  
     
    <plugin name="cordova-plugin-splashscreen" />
  
    <plugin name="org.apache.cordova.battery-status"/>
    <plugin name="org.apache.cordova.camera"/>
    <plugin name="org.apache.cordova.media-capture"/>
    <plugin name="org.apache.cordova.console"/>
    <plugin name="org.apache.cordova.contacts"/>
    <plugin name="org.apache.cordova.device"/>
    <plugin name="org.apache.cordova.device-motion"/>
    <plugin name="org.apache.cordova.device-orientation"/>
    <plugin name="org.apache.cordova.dialogs"/>
    <plugin name="org.apache.cordova.file"/>
    <plugin name="org.apache.cordova.file-transfer"/>
    <plugin name="org.apache.cordova.geolocation"/>
    <plugin name="org.apache.cordova.globalization"/>
    <plugin name="org.apache.cordova.inappbrowser"/>
    <plugin name="org.apache.cordova.media"/>
    <plugin name="org.apache.cordova.network-information"/>
    <plugin name="org.apache.cordova.vibration"/>
 
    <icon src="icon.png"/>
    <icon src="res/icon/android/icon-36-ldpi.png" platform="android" qualifier="ldpi"/>
    <icon src="res/icon/android/icon-48-mdpi.png" platform="android" qualifier="mdpi"/>
    <icon src="res/icon/android/icon-72-hdpi.png" platform="android" qualifier="hdpi"/>
    <icon src="res/icon/android/icon-96-xhdpi.png" platform="android" qualifier="xhdpi"/>
    <icon src="res/icon/blackberry/icon-80.png" platform="blackberry"/>
    <icon src="res/icon/blackberry/icon-80.png" platform="blackberry" state="hover"/>
  
    <icon src="res/icon/ios/icon-57.png" platform="ios" width="57" height="57"/>
    <icon src="res/icon/ios/icon-72.png" platform="ios" width="72" height="72"/>
    <icon src="res/icon/ios/icon-76.png" platform="ios" width="76" height="76"/>
    <icon src="res/icon/ios/icon-57-2x.png" platform="ios" width="114" height="114"/>
    <icon src="res/icon/ios/icon-120.png" platform="ios" width="120" height="120"/>
    <icon src="res/icon/ios/icon-72-2x.png" platform="ios" width="144" height="144"/>
    <icon src="res/icon/ios/icon-152.png" platform="ios" width="152" height="152"/>
  
    <icon src="res/icon/webos/icon-64.png" platform="webos"/>
    <icon src="res/icon/windows-phone/icon-48.png" platform="winphone"/>
    <icon src="res/icon/windows-phone/icon-173-tile.png" platform="winphone" role="background"/>
  
    <splash src="splash.png" />

    
    <splash src="res/screen/android/ldpi.png" platform="android" qualifier="port-ldpi"/>
    <splash src="res/screen/android/mdpi.png" platform="android" qualifier="port-mdpi"/>
    <splash src="res/screen/android/hdpi.png" platform="android" qualifier="port-hdpi"/>
    <splash src="res/screen/android/xhdpi.png" platform="android" qualifier="port-xhdpi"/>
    <splash src="res/screen/android/xxhdpi.png" platform="android" qualifier="port-xxhdpi" />
    
    <splash src="res/screen/ios/Default.png" platform="ios" width="320" height="480"/>
    <splash src="res/screen/ios/Default@2x.png" platform="ios" width="640" height="960"/>
    
    <splash src="res/screen/ios/Default-568h.png" platform="ios" width="320" height="568"/>
    <splash src="res/screen/ios/Default-568h@2x.png" platform="ios" width="640" height="1136"/>
    
    <splash src="res/screen/ios/Default-667h@2x.png" platform="ios" width="750" height="1334" />
    <splash src="res/screen/ios/Default-Portrait-736h@3x.png" platform="ios" width="1242" height="2208" />
    <splash src="res/screen/ios/Default-Landscape-736h@3x.png" platform="ios" width="2208" height="1242" />
    
    <splash src="res/screen/ios/Default-Portrait.png" platform="ios" width="768" height="1024"/>
    <splash src="res/screen/ios/Default-Landscape.png" platform="ios" width="1024" height="768"/>
    
    <splash src="res/screen/ios/Default-Portrait@2x.png" platform="ios" width="1536" height="2048"/>
    <splash src="res/screen/ios/Default-Landscape@2x.png" platform="ios" width="2048" height="1536"/>
    
    <splash src="res/screen/windows-phone/screen-portrait.jpg" platform="winphone"/>

    <access origin="*"/>
    <plugin name="cordova-plugin-whitelist" version="1"/>
    <allow-intent href="http://*/*"/>
    <allow-intent href="https://*/*"/>
    <allow-intent href="tel:*"/>
    <allow-intent href="sms:*"/>
    <allow-intent href="mailto:*"/>
    <allow-intent href="geo:*"/>
    <platform name="android">
    <allow-intent href="market:*"/>
    </platform>
    <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
    </platform>
    </widget>

**Comment by Farufon** [comment]
Well, that lasted for 3 hours.  Then tried again with PGB, and it built fine.  As if the server just started crapping out.  Throwing errors, even an unable to que error started coming.  

Still, no change to the files.

**Comment by andersborgabiro** [comment]
PGB might be overloaded or the PGB team might be updating. (Sh)it happens.

From what I can see your config.xml is fine.

**Comment by wildabeast** [comment]
Closing as apparently was termporary.
