### ISSUE TITLE
Apple Export Compliance Alert

### ISSUE THREAD

**Issue by Farufon** [phonegap/build#503]
How do we deal with this issue, while using PhoneGap Build.  It requires us to Insert this into info.plist

"It is your responsibility to comply with export regulations, and you should revisit these questions if your encryption or exemption status changes. If your encryption and exemption eligibility stay the same, use the following key-value pair in your Info.plist to provide export compliance information within your build:

    <key>ITSAppUsesNonExemptEncryption</key><false/>

**Comment by goya** [comment]
consider adding the key and value to the plist as shown here:

http://docs.build.phonegap.com/en_US/configuring_config_file_element.md.html#Config%20File%20Elements

**Comment by istr** [comment]
@goya The documentation you refer to is plain wrong. It is missing the fact that you need to use the ```gap:``` name space for the config to have an effect. See #512. The [working code snippet is posted on stackoverflow](http://stackoverflow.com/questions/35966608/adding-custom-parameter-phonegap-build/36496628):

```xml
<gap:config-file platform="ios" parent="ITSAppUsesNonExemptEncryption" mode="add">
<false/>
</gap:config-file>
```

**Comment by goya** [comment]
thanks for the heads up! fixed that.

**Comment by toddmedema** [comment]
Hey all,

This doesn't seem to be working for me. Added that line to the bottom of my config.xml file just before the closing /widget:
```
<gap:config-file platform="ios" parent="ITSAppUsesNonExemptEncryption" mode="add">
    <false/>
  </gap:config-file>
```
And after deleting the iOS folder and running both `cordova platform add ios` AND `cordova build ios`, the key still isn't showing up in my plist file.

Running Cordova 6.1.1

Please advise, thank you!

**Comment by istr** [comment]
@toddmedema This applies to [Adobe's phonegap builder](https://build.phonegap.com/) only. Are you using this? Else you need to set this directly in your Info.plist file directly.

**Comment by jorgemartinez178** [comment]
Hello everyone, I am trying to publish in testflight the app I developed with phonegap, this app has nothing encrypted but I get the error "missing compliance" even when I indicate that it has nothing encrypted and also when I put the code 

`<gap:config-file platform="ios" parent="ITSAppUsesNonExemptEncryption" mode="add">
<false/>
</gap:config-file>
`

 and then I upload it, it does not appear in testflight but only in activity.

If someone has an idea of what is happening, I would appreciate your help.

**Comment by istr** [comment]
@jorgemartinez178 just to be sure: are you using the online Adobe PhoneGap Builder (https://build.phonegap.com/)? The recipe / entry above applies to the config for that building platform **only**. If you are using a "native" / local PhoneGap build you need to put the flag directly into Info.plist or provide the flag by other means specific to your build tool.

**Comment by jorgemartinez178** [comment]
Yes, I'm using https://build.phonegap.com.

**Comment by ef33zy** [comment]
@jorgemartinez178 you may need to answer the compliance questions in itunesconnect. See the [Apple FAQ page](https://itunespartner.apple.com/en/apps/faq)

To begin the questionnaire:

- Go to the Encryption section under Features in [My Apps](https://www.apple.com/itunes/go/itunesconnect/manageApps).
- Click the plus sign next to the appropriate platform section.
- Answer the questions and attach the compliance documents when prompted.
- Click Save.

![image](https://user-images.githubusercontent.com/15075449/28960036-f20717d4-78f4-11e7-89f4-f6e673c9c805.png)

**Comment by goya** [comment]
@jorgemartinez178 please open a discussion at https://forums.adobe.com/community/phonegap/build for further troubleshooting.
