### ISSUE TITLE
Plugin section (for git) has terrible example

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/build#505]
The new addition for git as [described in the blog](http://phonegap.com/blog/2016/02/16/git-plugins/) appears to be working for people.

The [documentation](http://docs.build.phonegap.com/en_US/configuring_plugins.md.html) (under *Plugin Source*) has a **terrible example**:

`<plugin spec="apache/cordova-plugin-file.git#4.1.0'>https://github.com/apache/cordova-plugin-file.git#4.1.0" /> `
`<plugin spec="apache/cordova-plugin-file.git#4.1.0'>https://github.com/apache/cordova-plugin-file.git#4.1.0" source="git" />`

**Comment by jessemonroy650** [comment]
**On Nitobi**
- [Unable to use plugin from Git - Cannot find plugin.xml for plugin '.'](http://community.phonegap.com/nitobi/topics/unable-to-use-plugin-from-git-cannot-find-plugin-xml-for-plugin)

**Comment by wildabeast** [comment]
Original issue fixed, thanks.

**Comment by jessemonroy650** [comment]
Thanks. +1 for Phonegap team.
