### ISSUE TITLE
[Windows, cli-6.0.0] PublisherDisplayName issue

### ISSUE THREAD

**Issue by mcxnet** [phonegap/build#506]
When I upload the new .appx file to the Windows App Store, I receive this error:
*****
Package acceptance validation error: The PublisherDisplayName element in the app manifest of app.appx is [my name and surname], which doesn't match your publisher display name: [my company... indicated in the "Publisher display name" contact info section].
*****

The issue is only with the latest cli-6.0.0 (.appx). 
With previous cli-5.4.1 or cli-5.2.0 (.xap) works good.

**Comment by wildabeast** [comment]
As per [this conversation](https://forums.adobe.com/thread/2111557).

Thanks for pointing this out. We've deployed a couple of fixes, here's how you should configure your app:
 
- _Publisher Name_: will be set to what you have set in the <author></author> field in config.xml
- _Display Name_: will be what you have set in the <name></name> field in config.xml
- _Package Identity Name_: added a new preference: windows-identity-name. retrieve this value from App Management --> App Identity in the Dev Center
- _Package Family Name_: will be generated based on the identity name
 
So as long as you have your Publisher ID set on Build and the following set to the correct values in your config.xml (sample values below):
 
    <author>Adobe</author>  
    <name>PhoneGap Build App</name>  
    <preference name="windows-identity-name" value="PhonegapBuild.PhoneGapBuild" />  
 
submission should be successful. Let us know if you still see errors.

**Comment by vinomano90** [comment]
@mxkeke can you tell me the steps to generate .appx with signature certificate to install it into another system.

And i need one more help if you can ? I want to generate a .exe file from ionic 3 can you tell me the steps to create .exe for the ionic v3 app.
