### ISSUE TITLE
Normal (Internal) link to external website opens in Safari on iOS after upgrade to cli-6.0.0 

### ISSUE THREAD

**Issue by MyBrainNL** [phonegap/build#508]
I just tested this again with a recompile; it still fails... 

My App has a normal link, (a href), to an external website, which should open within the App itself. This works fine in Android. But in iOS it opens externally in Safari when compiled with cli-6.0.0. Compiled with cli-5.2.0 it does open in the App, no problem there. I do have the whitelist plugin added and allow-navigation, allow-intent and access origin are all set to * 

So, I think it's a bug.

Also see:  http://community.phonegap.com/nitobi/topics/normal-internal-link-to-external-website-opens-in-safari-on-ios-after-upgrade-to-cli-6-0-0

**Comment by MyBrainNL** [comment]
Found it!
After being pointed in the right direction on Jira... it was the allow-intent that is causing this behavior.

Using 

<allow-intent href="*" />

or leaving this whole line out of the config, causes iOS to open safari.

However, using the following in the config does work correctly:

    <allow-intent href="tel:*" />	
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

And I thought using the * would be the easy way to configure this :-)
Hope this helps anyone else with the same problem.

**Comment by razisyed** [comment]
Hi, I have the same problem, but this did not resolve it for me. It works right for android, but on ios, it keeps opening all links in safari. My config in github repository is at https://github.com/razisyed/inspectform/blob/master/InspectFormCordova/config.xml. Any help will be greatly appreciated!

**Comment by wildabeast** [comment]
@razisyed can you please open a discussion at https://forums.adobe.com/community/phonegap/build
