### ISSUE TITLE
Phonegap/build app install does not work on only 1 iOS testing devices...

### ISSUE THREAD

**Issue by vanessabt** [phonegap/build#510]
We have completed a build for an app and are in the testing phase to see how it works on various devices and how the installation works. I have installed the app on 3 tester iphones, and ipad and and 3 android devices with no problem. However, I have one iphone that I am testing with our client and for some reason the app just will not install. The concern is that this may happen to other devices if we launch this. 

I have confirmed the devices UDID by plugging it into Itunes. I have registered the device and created the provisioning file... I actually deleted it and recreated it in case there was an issue with the file but that did not work. 

When installing, the icon stays on the home screen, but fails to install and responds with “unable to download app – DC 711 could not be installed at this time”. When we scan the QR code and click on install it replies “Frame Load interrupted”. 

When we re-drag in the provisioning file it doesn't seem to ask us to replace like it does on the other devices if you drag it in again. 

Any thoughts or ideas for additional problem solving so I can get this issue resolved? The Iphone is is an Iphone 6 running ios 9.2.1.

any suggestions?

**Comment by wildabeast** [comment]
Replied to your [original thread](https://forums.adobe.com/thread/2117822).

**Comment by wildabeast** [comment]
Original thread marked as resolved.
