### ISSUE TITLE
Git LFS support

### ISSUE THREAD

**Issue by fishie** [phonegap/build#511]
GitHub now supports Git LFS (https://git-lfs.github.com/) "An open source Git extension for versioning large files". However, PhoneGap Build does not seem to support it yet. I have reverted to uploading a zip-file for this reason but it would be a lot faster and more convenient if the pull from Git repository function in PhoneGap Build supported Git LFS. The setup is rather trivial and after it has been setup it requires no extra actions for someone who merely pulls as it works transparently with a regular git pull. It does however add an extra step of the pull that adds another point of failure, but it does so only for repositories that use Git LFS anyway.

Thank you!

**Comment by goya** [comment]
so what happens when you enter a git url that has lfs? does it fail the clone? 

do you have a repo that i can reproduce the failure? i am able to add an app that uses lfs successfully

**Comment by goya** [comment]
added.

**Comment by miraclemaker** [comment]
This doesn't appear to be working. See: https://forums.adobe.com/thread/2515111
