### ISSUE TITLE
gitlab support

### ISSUE THREAD

**Issue by nagashik** [phonegap/build#513]
I have connected my gitlab account.
now I use URL https://gitlab.com/v.gordeenkov/phonegap.git to create App from this repo. And it writes to me: unable to clone/checkout repository https://gitlab.com/v.gordeenkov/phonegap.git

What should I write in the field "paste .git repo" for private gitlab repo to make it work in proper way?

thank you in advance

**Comment by goya** [comment]
your url is correct. 

seems an issue is already filed on this: https://gitlab.com/gitlab-org/gitlab-workhorse/issues/36

i'll keep you posted, we do try and do shallow clones as much as possible for bandwidth.

**Comment by goya** [comment]
this seems to be resolved on gitlab's side.
