### ISSUE TITLE
iOS 9: phonegap cli-6.0.0 always using the default icon

### ISSUE THREAD

**Issue by vsxed** [phonegap/build#514]
Since version cli-6.0.0 + PGB my application's always getting the default icon. The paths are correct (were working with older phonegap versions) but totally ignored

Device: iPhone 6S w/ iOS 9.1
PGB, phonegap cli-6.0.0

**Comment by wildabeast** [comment]
Can you post your icon declarations and/or your app I'd?

**Comment by vsxed** [comment]
AppId: 1965636

This is my reference code for icons:

`<icon src="icon.png" />
    <platform name="ios">
        <icon height="60" src="res/icon/ios/icon-60.png" width="60" />
        <icon height="120" src="res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" src="res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="76" src="res/icon/ios/icon@76.png" width="76" />
        <icon height="152" src="res/icon/ios/icon-76@2x.png" width="152" />
    </platform>
    <platform name="android">
        <icon qualifier="ldpi" src="res/icon/android/icon-36-ldpi.png" />
        <icon qualifier="mdpi" src="res/icon/android/icon-48-mdpi.png" />
        <icon qualifier="hdpi" src="res/icon/android/icon-72-hdpi.png" />
        <icon qualifier="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
        <icon qualifier="xxhdpi" src="res/icon/android/icon-144-xxhdpi.png" />
        <icon qualifier="xxxhdpi" src="res/icon/android/icon-192-xxxhdpi.png" />
    </platform>`

**Comment by wildabeast** [comment]
Your icons reside in `res/icons/` but your src paths have `res/icon/`(add an s).
