### ISSUE TITLE
StatusBar Plugin Issue

### ISSUE THREAD

**Issue by MahmoudFawzy** [phonegap/build#518]
this plugin StatusBar 
https://build.phonegap.com/plugins/715
not  support all plat form within in description. told it's support. 
https://github.com/apache/cordova-plugin-statusbar/blob/bdbaf129595c4a4e3d957a1bc218d05dc5f82a9e/README.md

**Comment by wildabeast** [comment]
Use the npm version:

    <plugin name="cordova-plugin-statusbar" />
