### ISSUE TITLE
Docs are broken when viewed with Chrome

### ISSUE THREAD

**Issue by grokcode** [phonegap/build#519]
The docs are unusable on Chrome (Version 48.0.2564.116 (64-bit) on OSX). Since a picture is worth a thousand words, here is the same [page](http://docs.build.phonegap.com/en_US/2.9.0/configuring_config_file_element.md.html) viewed with Chrome: 
![screen shot 2016-05-16 at 4 28 23 pm](https://cloud.githubusercontent.com/assets/61232/15306890/469c10ae-1b83-11e6-8b1e-70c08746ae7f.png)
Safari:

![screen shot 2016-05-16 at 4 30 29 pm](https://cloud.githubusercontent.com/assets/61232/15306939/94e0b94a-1b83-11e6-80c1-848139ebbe6f.png)

There are a number of JS errors in the Chrome console: 
![screen shot 2016-05-16 at 4 32 42 pm](https://cloud.githubusercontent.com/assets/61232/15306979/d93d7b0a-1b83-11e6-9436-91c058f559c6.png)

Apologies in advance if this isn't the proper place for reporting this issue.

**Comment by wildabeast** [comment]
I'm unable to reproduce the rendering issue on Chrome (50.0).

Might be noteworthy that the page you've linked is an old version of the docs (we no longer have the versions in the url), and you can't navigate to it from the [current docs](http://docs.build.phonegap.com/en_US/index.html).

But the JS errors are occuring on our current docs too, so we've noted that. Thanks for reporting.

**Comment by grokcode** [comment]
Thanks @wildabeast! It looks like there is a Chrome upgrade in my future.

As a datapoint, the current docs look great on Chrome 48. Most (all?) of my google searches land on the old docs, not the new ones, so even though there is no way to navigate there from the current docs, my guess is those pages are still getting a lot of traffic.

**Comment by wildabeast** [comment]
Strange though, I would be surprised if the Chrome version was the source of the rendering issue... If you were to inspect the broken page with the Chrome dev tools, I'd be curious to see if / why the CSS isn't loading.

And excellent point re google searches. Definitely worth us handling those old urls appropriately.

**Comment by grokcode** [comment]
After a bit more investigation, it looks like this is an issue only when the Chrome Markdown Preview extension is installed. I think it must be picking up the `.md.html` from the url and then trying to do some markdown processing on the page which breaks everything. So not as issue with the docs after all. Thanks for working through that with me!

**Comment by goya** [comment]
docs have moved to the primary phonegap.com docs site and has been redesigned.
