### ISSUE TITLE
Windows platform using CLI-6.1.0 does not build

### ISSUE THREAD

**Issue by leewalkergm** [phonegap/build#520]
Using CLI-6.1.0, Windows does not build at all, failing with the following problem:

```
CertUtil: -importPFX command FAILED: 0x80070056 (WIN32: 86 ERROR_INVALID_PASSWORD)
CertUtil: The specified network password is not correct.
```

**Comment by brodybits** [comment]
Did anyone have a chance to look at this? I wonder if #530 (problem with PhoneGap Build) may be related or not.

**Comment by ef33zy** [comment]
@leewalkergm I wonder if you have the same scenario as given [here](https://forums.adobe.com/message/8957411#8957411)

**Comment by leewalkergm** [comment]
I think the problem is similar, but the solution hasn't worked for us

**Comment by wildabeast** [comment]
Was a hiccup on Build, should be good to go now.
