### ISSUE TITLE
[build] PGB builds Windows10 x86 only, disregarding preferences in config.xml

### ISSUE THREAD

**Issue by tonijn** [phonegap/build#528]
It seems that every build comes out as a Windows10 x86 package.
Config.xml settings don't work. I have tried every combination, f.e:

```
<!-- Windows Phone 8.1: -->
<preference name="windows-appx-target" value="8.1-phone"/>
<preference name="windows-arch" value="anycpu" />
```

Result: CordovaApp.Windows10_2.0.8.0_x86.appx
```
Building project: C:\cygwin\tmp\gimlet\1530672\project\CordovaApp.Windows10.jsproj
	Configuration : release
	Platform      : x86
```

Phonegap cli-6.1.0, cordova-windows 4.3.1

**Comment by goya** [comment]
unable to reporoduce, do you have an appid or github repo that can reproduce this issue?

**Comment by tonijn** [comment]
Thank you Brett,

app id is 1530672

**Comment by wildabeast** [comment]
Looks like those preferences are getting ignored when they're inside a `<platform name="windows"></platform>` tag. This is a bug, but as a workaround you can put them outside the `platform` tag.

Let me know if that works for you.

**Comment by tonijn** [comment]
Thank you Ryan,

Succes. The suggested method works.

**Comment by wildabeast** [comment]
FYI wrapping these prefs in the windows platform tag should now work as expected:

    <platform name=windows">
        <preference name="windows-appx-target" value="8.1-phone"/>
        <preference name="windows-arch" value="anycpu" />
    </platform>
