### ISSUE TITLE
IOS XCODE build error: resources/cvcapture.bundle no such file or directory" 

### ISSUE THREAD

**Issue by AnbuIOS** [phonegap/build#531]
HI Team,

While Build the ios mobile applcation in xcode "resources/cvcapture.bundle no such file or directory" error occurred .

kindly provide the sollution .
screenshot attached.

kindly provide the sollution to fix this issue.****
![ios error](https://cloud.githubusercontent.com/assets/20415344/16764705/62c11dd2-484d-11e6-828c-2befd14069da.png)
Thanks
Anbazhahan M

**Comment by wildabeast** [comment]
Hi, this issue tracker is for issues with build.phonegap.com. For issues with building phonegap locally, try https://forums.adobe.com/community/phonegap.
