### ISSUE TITLE
Preferences since 6.0.0

### ISSUE THREAD

**Issue by svmotin** [phonegap/build#532]
Starting from phonegap-cli version 6.0.0 phonegap build ignors preferences for ios like deployment-target, target-device in config.xml and uses it's default values.

**Comment by matthewgertner** [comment]
I can confirm this for `target-device` at least. We have it set to "handset", which caused iPhone-only builds on iOS in the past. When we built with 6.3.0 then iTunes Connect started to complain again about missing iPad images. When I checked `Info.plist`, the setting for iPad is back so the pref seems to be ignored.

**Comment by wildabeast** [comment]
`target-device` and `deployment-target` preferences should be fixed for iOS now on Build:

    <preference name="target-device" value="handset" />
    <preference name="deployment-target" value="8.0" />
