### ISSUE TITLE
phonegap build with cordova-plugin-splashscreen

### ISSUE THREAD

**Issue by svmotin** [phonegap/build#534]
When building an apk with phonegap build using cordova-plugin-splashscreen the app fails at the start on android 4.4.4 and lower.

**Comment by ef33zy** [comment]
@svmotin did you specify a minimum android version in your `config.xml` as example below?

`<preference name="android-minSdkVersion"	  	value="19" />`

Have you tried debugging? Any errors shown?

**Comment by svmotin** [comment]
yes i have <preference name="android-minSdkVersion" value="15" />

No, i have not tried debugging becase i don't know how to do it with build but there are no errors in the build log.

**Comment by kleeb** [comment]
I am using cordova-plugin-splashscreen and tested even on Android 4.1. No failures.
I guess its a problem with the app or configuration not the plugin or build itself.
