### ISSUE TITLE
Errors saying build failed and various plugin need updating

### ISSUE THREAD

**Issue by danzen** [phonegap/build#535]
I have an app that was building fine a few months ago and now returning to it with cli 6.3.0 it will not build with the plugins I had requested despite using the generic latest plugin format:

`<gap:plugin name="org.apache.cordova.inappbrowser" />`
`<gap:plugin name="org.apache.cordova.file-transfer" />`
`<gap:plugin name="org.apache.cordova.media" />`

This tells me:

_Error - The following core plugin is causing the build to fail and may need to be updated to a newer version: inappbrowser_

If I remove inappbrowser it says the same for "file" (although it should have said file-transfer) and if I remove that it says the same for "media".

I have tried the specific format for the last successful build - for instance:
`<plugin name="org.apache.cordova.media" source="pgb" spec="0.2.16" />`
This still gives the same error message.  I have tried several whitelist settings such as:
`<plugin name="cordova-plugin-whitelist" spec="1.2.2" />`

I have deleted the app and created it again - and still the same problem and yet when I remove all the plugin calls it builds fine.  I am actually not even using the plugins as I reduced the file to test other things - but I will need them to continue.

I am building from the following:
https://github.com/danzen/Vault7/tree/master/www

Any thoughts?

**Comment by wildabeast** [comment]
Your plugins should look like this:

<plugin name="cordova-plugin-inappbrowser" />

You are using a deprecated format.
