### ISSUE TITLE
Build for Windows does not overwrite 7 of the 15 default images

### ISSUE THREAD

**Issue by jayleew** [phonegap/build#536]
There are 15 default images found in the \images directory of the .appx package that results from a PGB build.  7 of those 15 images are never touched, no matter the settings found in config.xml.  There are 3 of the 7 images that, if submitted to the Windows Store, will not pass certification.  We are a paying PGB customer and need to now consider migrating to a Visual Studio solution.  We'd prefer not to spend the initial time migrating and bug testing, and hope that PGB can fix this issue before we have no choice.  More detailed information can be found: https://forums.adobe.com/message/8915806

Attached are the zip file uploaded, and the resulting .appx.   I placed the .appx in the zipfile, along with the source.
[css.zip](https://github.com/phonegap/build/files/399802/css.zip)

  This sample code was taken from https://github.com/phonegap/phonegap-template-hello-world

1. The plugins were modified in the source config.xml.
2. The \www directory was added to the stucture due to the settings in config.xml.  

These are the only 2 things changed in the source to get the .appx to build correctly.

**Comment by wildabeast** [comment]
Hi, looking into this.

**Comment by wildabeast** [comment]
Hi, we've added support for the missing images (and updated the [docs](http://docs.phonegap.com/phonegap-build/configuring/icons-and-splash/) ). The additions are as follows:

icons:

    <icon platform="winphone" width="70"  height="70"  src="res/icon/windows/Square70x70Logo.scale-100.png" />
    <icon platform="winphone" width="30"  height="30"  src="res/icon/windows/Square30x30Logo.scale-100.png" />
    <icon platform="winphone" width="310" height="310" src="res/icon/windows/Square310x310Logo.scale-100.png" />
    <icon platform="winphone" width="50"  height="50"  src="res/icon/windows/StoreLogo.scale-100.png" />
    <icon platform="winphone" width="120" height="120" src="res/icon/windows/StoreLogo.scale-240.png" />

splash:

    <splash platform="winphone" width="620" height="300" src="res/screen/windows/SplashScreen.scale-100.png" />

**Comment by jayleew** [comment]
I tested this and it works.  The only caveat I found is the dimensions of the StoreLogo.scale-100.png must be width="50" height="50".  This works when platform is set to "windows" or "winphone"

If you try width="100" height="100".  The file does not get overwritten in the build.

I'm not sure if this is intentional or not, but this is excellent progress.  Thank you.

**Comment by wildabeast** [comment]
This is exepcted. The 100 in `StoreLogo.scale-100.png` is not referring to a dimension -- it is a scale multiplier (100%). Notice that `StoreLogo.scale-240.png` has dimensions 120x120 (240%).
