### ISSUE TITLE
Starting app in landscape on iPad messes up layout

### ISSUE THREAD

**Issue by Duwo25** [phonegap/build#538]
Hi,
A few weeks ago I started using Phonegap Build and overall I'm very happy with it. However, I did ran into the following issue:
When I start the app in landscape mode, the layout of the app is messed up and there is no way to correct it, besides stopping the app and starting it in portrait mode. Once it's started in portrait, you can easily switch between landscape and portrait without any issues.
Here's a screen shot of the messed up layout (the content all appears in the lower right corner.
![landscape-bad](https://cloud.githubusercontent.com/assets/20885753/17461855/33fdf84c-5c9a-11e6-9197-2f1b196c2f5e.png)
Here's what is should look like (and what you get if you start the app in portrait and the switch to landscape).
![landscape-good](https://cloud.githubusercontent.com/assets/20885753/17461856/37578238-5c9a-11e6-9e22-847cd5f1f9fd.png)
I'm using iOS 9.3.3 and Phonegap cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1).

**Comment by wildabeast** [comment]
Hrm have you tried playing with the viewport settings?

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />

**Comment by Duwo25** [comment]
Thanks for the suggestion.
I had that in my index.html file, but without the minimum-scale, maximum-scale and user-scalable attributes, so I added those. Unfortunately it doesn't make any difference. The result is exactly the same.

**Comment by Duwo25** [comment]
The same app works just fine on Android tablets. It seems to be an iOS only issue.

**Comment by Duwo25** [comment]
This seems to have been fixed somehow. Maybe through an iOS update, because I didn't change anything on my app side.
