### ISSUE TITLE
Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: nl.x-services.plugins.socialsharing

### ISSUE THREAD

**Issue by bloomsoft** [phonegap/build#539]
"Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: nl.x-services.plugins.socialsharing"

This was working fine till my last built on some where around 27-28th of July 2016 but now today on Aug 08, 2016 it has started giving this error:

I have checked in plugins list there is no further build version of this plugin has been added to plugins directory build.phonegap

so please help me sorting out this issue so I can build the app.

Thanks

**Comment by wildabeast** [comment]
Are you declaring a `phonegap-version` in your config.xml? PGB recently updated the default build version from `cli-5.2.0` to `cli-6.3.0`. If you weren't declaring a version, you would be using the new default. So try locking to the old default of `cli-5.2.0`.

    <preference name="phonegap-version" value="cli-5.2.0" />

Alternatively perhaps you have locked to an old version of the social sharing plugin -- try using the latest version.

**Comment by wildabeast** [comment]
Actually I see some responses in your [forums post](https://forums.adobe.com/thread/2192539) -- follow those.

**Comment by bloomsoft** [comment]
Thanks wildabeat, your answer worked.
