### ISSUE TITLE
[Collaborators] - Add ability to cancel invitation

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#54]
Feature request to add the ability to cancel invitation from pending acceptance list

Related issue:
http://community.phonegap.com/nitobi/topics/how_do_i_remove_pending_acceptance_collaborators

**Comment by eltuctuc** [comment]
can you fix this problem

**Comment by amirudin** [comment]
Related topic:
https://getsatisfaction.com/nitobi/topics/delete-collaborators

**Comment by Heshyo** [comment]
I've had the same as @henrikhermansen for a very long time. I invited several email addresses. Those who never accepted are forever in pending acceptance and I can't remove them, those who accepted are shown twice: once as accepted (with the edit/delete buttons) and once as pending acceptance.

Topics related to not being able to remove pending invitations:
http://community.phonegap.com/nitobi/topics/cant_remove_pending_contributor_invites
http://community.phonegap.com/nitobi/topics/remove-pending-acceptance-collaborators

Topics and bugs related to invitations shown as accepted and pending:
https://github.com/phonegap/build/issues/82
http://community.phonegap.com/nitobi/topics/found-a-bug-on-collaborators-screen
http://community.phonegap.com/nitobi/topics/duplicate-collaborators

**Comment by Parsnip** [comment]
4 years later this is still a problem, as is the duplicate collaborator issue mentioned above.

**Comment by wildabeast** [comment]
Fixed! :beers: 🎉
