### ISSUE TITLE
config.xml properties removed by build service

### ISSUE THREAD

**Issue by szh** [phonegap/build#541]
I'm using the [cordova-hot-code-push](https://github.com/nordnet/cordova-hot-code-push) plugin, which requires some extra properties in the config.xml of my app. When I build the app for Android using PhoneGap Build, the properties are not copied to the .apk. (I haven't tested for other operating systems.)

The input config.xml looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.example.myapp" version="0.0.1" xmlns="http://www.w3.org/ns/widgets">
  <name>My App</name>
  <description>App description...</description>
  <author href="http://www.example.com" email="dev@example.com">My Company</author>
  <content src="index.html"/>
  <icon src="icon.png"/>

  <access origin="*"/>
  <plugin name="cordova-plugin-whitelist" spec="~1.2" source="npm" />
  <plugin name="cordova-plugin-dialogs" spec="~1.2" source="npm" />
  <plugin name="cordova-plugin-secure-storage" spec="~2.4" source="npm" />
  <plugin name="cordova-hot-code-push-plugin" spec="~1.4" source="npm" />

  <chcp>
    <config-file url="http://example.com/mobile_repo/chcp.json" />
    <native-interface version="1" />
  </chcp>

  <platform name="ios">
    <preference name="KeychainAccessibility" value="WhenPasscodeSetThisDeviceOnly"/>
    <preference name="UIWebViewBounce" value="false"/>
    <preference name="deployment-target" value="8.0" />
  </platform>


  <platform name="android">
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="23" />
  </platform>

  <preference name="loadUrlTimeoutValue" value="700000" />
  <preference name="DisallowOverscroll" value="true" />

</widget>
```

When I run the app, the plugin can't find the properties. I used apktool to decode the compiled config.xml in the .apk and it doesn't have the properties. I found this issue documented [here](https://github.com/nordnet/cordova-hot-code-push/issues/118#issuecomment-196698276) as well.
Not only that, but much of the app info is replace with sample data, and more whitelist properties are added. Here's the output xml - notice that only the plugins and preferences are preserved:
```xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="io.cordova.helloCordova" version="2.0.0" xmlns="http://www.w3.org/ns/widgets">
    <name> Hello Cordova
</name>
    <description> A sample Apache Cordova application that responds to the deviceready
        event. </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io"> Apache Cordova Team </author>
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="market:*" />
    <preference name="loglevel" value="DEBUG" />
    <feature name="Whitelist">
        <param name="android-package" value="org.apache.cordova.whitelist.WhitelistPlugin" />
        <param name="onload" value="true" />
    </feature>
    <feature name="Notification">
        <param name="android-package" value="org.apache.cordova.dialogs.Notification" />
    </feature>
    <feature name="SecureStorage">
        <param name="android-package" value="com.crypho.plugins.SecureStorage" />
    </feature>
    <feature name="HotCodePush">
        <param name="android-package" value="com.nordnetab.chcp.main.HotCodePushPlugin" />
        <param name="onload" value="true" />
    </feature>
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="23" />
    <preference name="loadUrlTimeoutValue" value="700000" />
    <preference name="DisallowOverscroll" value="true" />
    <content src="index.html" />
</widget>
```

**Comment by wildabeast** [comment]
This is expected behaviour. The `config.xml` file follows a spec, and tools (like build) won't support arbitrary elements.

The proper configuration for this would be for the cordova-hot-code-push plugin to support parameters for those configurations, and you would then declare it something like this:

    <plugin name="cordova-hot-code-push-plugin" spec="~1.4" source="npm">
        <param name="config-file-url" value="http://example.com/mobile_repo/chcp.json" />
        <param name="native-interface-version" value="1" />
    </plugin>

For a plugin that demonstrates this, have a look at the [PhoneGap Push Plugin](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md).

**Comment by szh** [comment]
OK, got it. But can you explain why the name, description, author, and whitelist info is being replaced? Thanks

**Comment by wildabeast** [comment]
What is the folder structure of the zip you are uploading? It should be just a www folder. A common mistake is to upload an entire PhoneGap / Cordova project directory (including native and plugin files), which can cause something like this..

**Comment by szh** [comment]
The zip file contains just config.xml, a www folder, and an icon.
