### ISSUE TITLE
Auto-update PhoneGap Build app installed on phone

### ISSUE THREAD

**Issue by ef33zy** [phonegap/build#542]
Hi,
 
I'm building my first app using PGB.
I have installed them on phones for the various platform OS, and they are working as expected.
However, I would like to update them without uninstalling everytime.
 
Is there a way to (auto)update the PGB app already installed on the phone? 
Either directly on PGB,  or via a notification or a plugin?
I've been reading about [ContentSync plugin](https://github.com/phonegap/phonegap-plugin-contentsync), and still not sure if it'll do the job.
Previously when I tried building the app with "Hydration" enabled, the app would sometimes get stuck in a state of "Initializing, please wait."

Looking forward to your help!

**Comment by ef33zy** [comment]
Hi,

Please any help on this?

**Comment by wildabeast** [comment]
Are you looking for updating your web assets during development? Or are you looking to be able to update your app after it has been pushed to app stores?

Hydration is a decent solution for development updates (the  'initializing' screen may get stuck if there are network connectivity issues). For production deployment, the content-sync plugin is a good option.
