### ISSUE TITLE
`.pgbomit` is not working as expected with duplicate folders

### ISSUE THREAD

**Issue by Eccenux** [phonegap/build#543]
I have two directories:
1. /css/ (in repo root) is my working directory. It contains unminified file and other stuff.
2. /_build/pgb/css/ is css that supposed to be in my app root.

Also note that `config.xml` is in `/_build/pgb/`.

So what PGB 6.3.0 seem to be doing is:
1. Attempt to copy `/_build/pgb/css/` to `/css/`, notices duplicate and skips it.
2. Then it notices `.pgbomit` in `/css/` and removes it.

Result:
`/css/` folder is not copied to `/assets/www/` at all.

Expected:
Omit `/css/` and then copy `/_build/pgb/css/` to `/css/`.

BTW. Why doesn't PGB simply use `/_build/pgb/`?! It did find `config.xml` (and `index.html`) in it. So why mess around with other folders?

**Comment by goya** [comment]
what app id is this so we can replicate

**Comment by Eccenux** [comment]
The app id is: 2213657

Note that it currently is build almost correctly. I've managed to trick the system by temporarily removing root `css` folder.

The repo is here: https://github.com/Eccenux/MyPokedex (`css` folder is now restored in it).
