### ISSUE TITLE
Issues with iOS icons using Cordova 6.x.x

### ISSUE THREAD

**Issue by matthewgertner** [phonegap/build#545]
I'm referencing https://github.com/phonegap/phonegap-cli/issues/636 here since it seems to be a PhoneGap Build issue. No matter which icons you specify, the default 87x87px icon (and apparently 167x167px) is used instead of the one specified. This makes PGB currently usable for any app targeting iPhone 6 Plus (i.e. pretty much any iPhone app).

**Comment by goya** [comment]
a fix has been pushed to production
