### ISSUE TITLE
ios build failed due core plugin device outdated !

### ISSUE THREAD

**Issue by isoundware** [phonegap/build#546]
Error - The following core plugin is causing the build to fail and may need to be updated to a newer version: device
/Plugins/org.apache.cordova.device/CDVDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Tried with and without plugin specified in config.xml

PLEASE FIX THE PROBLEM ASAP THANKS.
JH

**Comment by ef33zy** [comment]
@isoundware how have you specified the plugin in your config.xml file?

**Comment by isoundware** [comment]
Hi,
i have tried:
<plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
<plugin name="cordova-plugin-device" source="npm" />

also without specification of this plugin.

All with error.

Thanks. 
Jan

**Comment by goya** [comment]
please start an issue on the adobe forums: https://forums.adobe.com/community/phonegap/build

if you already have please place a link to the discussion here.

**Comment by browndp08** [comment]
https://forums.adobe.com/message/9003990#9003990 for future reference for anyone else
