### ISSUE TITLE
Build phonegap is buggy or something 

### ISSUE THREAD

**Issue by int21ve** [phonegap/build#549]
After compiling my project I'm trying to instal the app on both platforms (android & iPhone) and none of them work. Just hang on splash screen and do nothing.
I debugged android version and nothing showed in log cat.
But strangely when I compiled for Android with Cordova CLI everything works fines

**Comment by goya** [comment]
please start a discussion in our support forums: https://forums.adobe.com/community/phonegap/build so we can troubleshoot.

**Comment by int21ve** [comment]
Why it was close?

**Comment by goya** [comment]
please start a discussion at the support forums (https://forums.adobe.com/community/phonegap/build ) for support issues. this issue tracker is not for support issues for individual apps.
