### ISSUE TITLE
Adobe Build Support: Does It Exist?

### ISSUE THREAD

**Issue by quosoft** [phonegap/build#550]
What is the best method of obtaining support for Adobe Build? I am finding there are a number of unanswered issues which is making our organisation reconsider the use of Adobe Products for building Apps. Is this the right channel for support? Are there other channels?

The current issues are with Build:
- what is the licensing arrangements and how does this relate to file upload size?
- is there a need to attach to a Creative Cloud subscription? Is this a new or existing CC subscription ... what product should be subscribed to if only Build is required (i.e. a specific AdobeID is being used for Build purposes)?
- are there issues with uploading large zips over and above licensing arrangements (i.e. crashes out above about 75MB with no sensible error message)?
- are some issues browser related?

**Comment by LarsVoith** [comment]
I have uploaded 125mb zip with no problem using Safari -- "The new limits are 50MB for free tier users, 100MB for standalone users and 1GB for Creative Cloud subscribers."  
http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/

Or you can load in later with the content sync plugin
https://www.npmjs.com/package/phonegap-plugin-contentsync

**Comment by wildabeast** [comment]
- https://build.phonegap.com/plans
- If you're looking only for PhoneGap Build, you want the standalone license on the above page
- uploads above allowed maximums will receive an error -- if it simply times out its possible your connection is being interrupted. you may have better luck using the API on the command line

Questions like this are better taken to the [Adobe PhoneGap official support forum](https://forums.adobe.com/community/phonegap/build).
