### ISSUE TITLE
Phonegap plugin callbacks don't fire in iOS build

### ISSUE THREAD

**Issue by thelucre** [phonegap/build#551]
My Phonegap apps works great when serving locally to an iOS device. However, after installing the `.ipa` file from Phonegap Build, I'm seeing a strange behavior. When requesting a plugin command, the app doesn't seem to respond at all. When I double click the Home button, to show the open app summary view, then the plugin callback fires appropriately. It's the weirdest thing. It's happening on both the `geolocation` and `barcodescanner` plugins.

So the plugins are in the build and the callbacks are firing, but not until the app is "minimized". Because it's an issue for multiple plugins, I'm thinking it's related to the Build config. Any help would be greatly appreciated. 

config.xml: https://gist.github.com/thelucre/dd07998ad350b2916113a8c9a4823db4

Phonegap Build info:
`PhoneGap (iOS / Android / Windows)` 
`cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1)`

Confirmed issue on both iPhone 5s - 10.0.1 and iPad 4 - 9.5.3

**Comment by goya** [comment]
for issues relating to an app please post on the phonegap build support forums at: please include your app id # so we can troubleshoot.
