### ISSUE TITLE
Framework7 and phonegap build android problem

### ISSUE THREAD

**Issue by phuongtailtranminh** [phonegap/build#552]
Hi,

I'm trying to build an app with framework7 with phonegap for Android (API 23).

Everything works fine with "phonegap serve" command, and I tested on Phonegap Developer App.

But I tried on Android Emulator, when I navigated the log windows shows:

"Cannot call determinedVisibility()"

And the $$.ajax() is not working on Android Emulator.

Please help!

Thank you guys!

**Comment by goya** [comment]
for issues regarding single apps or javascript please flag it up on the support forums: https://forums.adobe.com/community/phonegap
