### ISSUE TITLE
ios build fails

### ISSUE THREAD

**Issue by pmaigne** [phonegap/build#553]
Following ios build failure a test case (testios1) was sent to Phonegap: The app is a form with a picture (png). it works very well for Android and fails for ios. Phonegap reports only one error line with code -0700 and no information to identify the anomaly.
Could you please help.

**Comment by wildabeast** [comment]
App ID?

**Comment by pmaigne** [comment]
The app name is   testios1   and the App ID is 2277289 (as shown in PhoneGap)
Thanks for your support

**Comment by pmaigne** [comment]
By changing the phonegap build version to cli-5.4.1, the build succeeded.
