### ISSUE TITLE
iOS Build Issues

### ISSUE THREAD

**Issue by slifer45** [phonegap/build#554]
I can't build. 

What should I do?

Some times this issue
Error - The following core plugin is causing the build to fail and may need to be updated to a newer version: dialogs

Some times this.

Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: com.phonegap.plugins.PushPlugin

I can't find how to fix it.

my config 
`<gap:plugin name="org.apache.cordova.device" spec="0.3.0" />`
`<gap:plugin name="org.apache.cordova.device-motion" spec="0.2.11"/>`
`<gap:plugin name="org.apache.cordova.device-orientation" spec="0.3.11" />`
`<gap:plugin name="org.apache.cordova.inappbrowser" source="npm" spec="1.5.0"/>`
`<gap:plugin name="org.apache.cordova.network-information" spec="0.2.15" />`
`<gap:plugin name="org.apache.cordova.splashscreen" spec="1.0.0" />`
`<gap:plugin name="org.apache.cordova.console" spec="0.2.13" /> `
`<gap:plugin name="org.apache.cordova.geolocation" spec="0.3.12" /> `
`<gap:plugin name="org.apache.cordova.dialogs" spec="0.3.0" /> `
`<gap:plugin name="com.phonegap.plugins.pushplugin" spec="2.5.0" /> `

**Comment by goya** [comment]
please post a comment in the forums for app support issues:https://forums.adobe.com/community/phonegap/build so we can troubleshoot.
