### ISSUE TITLE
Getting this message during Build. What does it mean? << ...plugins won't be accessible after Nov 15th, 2016 >>

### ISSUE THREAD

**Issue by bigz90210** [phonegap/build#555]
<< This app uses plugins from the PhoneGap Build repository. These plugins won't be accessible after Nov 15th, 2016 >>

Has anyone seen this? Which plugins are being phased out? It reads my config.xml and generates this message, but I don't know which plugins and why and what to do after 11/15/2016.

**Comment by goya** [comment]
the pgb repository is shutting down nov 15th

blog coming soon.
