### ISSUE TITLE
Choose platforms to build when updating code

### ISSUE THREAD

**Issue by Eccenux** [phonegap/build#557]
Would be very useful as it would allow quick build for single platform and would also lower PGB server load.

Something like on the modified screen below.
![pgb_platforms_build](https://cloud.githubusercontent.com/assets/1045235/19324482/245e4f5c-90c2-11e6-8fdb-9f172a35b858.png)

(screen is from zip-upload version of the update popup, but the same could be done for git-pull version of the popup)

**Comment by goya** [comment]
i can't us doing this as it would lead to diff platforms having different source code.

if different platforms require diff source code you can use _merges_ directories and if a project doesn't require a platform at all then it can just be removed in the config.xml by adding <platform /> tags and not including the platform that you want to ignore.

**Comment by Eccenux** [comment]
Having differences in platforms source code is currently possible -- Android will happily build without certificate and iOS will not. But that's not the point.

The point is I sometimes test a new plugin with one platform and then test with another. So I simply don't need other platforms to build. Obviously when I finish testing I build all platforms.
