### ISSUE TITLE
Media plugin from npm is significantly different from the one in pgb?

### ISSUE THREAD

**Issue by yunyun27** [phonegap/build#560]
Just learned plugins from pgb won't be accessible after Nov 15.
After changing the config file to get the media plugin from npm, I noticed a big difference.
Using media from pgb, you can preload sound files, and play them without any problem.
Using media from npm, if you preload multiple sound files, only the last one will be played.
 
For example:
var a = new Media(file1);
var b = new Media(file2);
a.play();
 
This works with pgb but not npm. 
It would be a big problem for our app since we need to preload sound files and play them later.
Could the media plugin from npm work like the one from pgb in this regard?  Thank you.

**Comment by goya** [comment]
if you know the tagged version that works on pgb eg 0.0.1 - it is IDENTICAL to that tagged version on npm or in the git repo for the plugin. the git location is displayed on the plugin info page.

**Comment by yunyun27** [comment]
Thanks, that's correct, adding spec='1.0.1' to the npm media plugin does get the one that can preload sound files.
However, I do notice that the latest npm media plugin has recording pause/resume which version 1.0.1 does not have. 
So it would be great if the latest npm media plugin works with preloading too.

**Comment by goya** [comment]
thats out of our control. you can add an issue on the cordova project: https://issues.apache.org/jira/browse/CB
