### ISSUE TITLE
Does not include referenced Windows project

### ISSUE THREAD

**Issue by brodybits** [phonegap/build#562]
When I build <https://github.com/brodybits/Cordova-sqlite-legacy-PGB-W10-x86-test-app> for Windows I get the following log:
```
Build Date: 2016-11-01 17:00:08 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-dialogs@~1.3.0" via npm
Installing "cordova-plugin-dialogs" at "1.3.0" for windows
Fetching plugin "https://github.com/litehelpers/Cordova-sqlite-legacy-build-support" via git clone
Using shallow clone
Repository "https://github.com/litehelpers/Cordova-sqlite-legacy-build-support" checked out to git ref "master" at "9d28834".
Installing "cordova-sqlite-legacy-build-support" at "1.3.4" for windows
Building project: C:\cygwin\tmp\gimlet\2334122\project\CordovaApp.Windows10.jsproj
	Configuration : debug
	Platform      : x86
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1610,5): warning : The referenced project '..\..\cordova\plugins\cordova-sqlite-legacy-build-support\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj' does not exist. [C:\cygwin\tmp\gimlet\2334122\project\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(4330,5): warning MSB3202: The project file "..\..\cordova\plugins\cordova-sqlite-legacy-build-support\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj" was not found. [C:\cygwin\tmp\gimlet\2334122\project\CordovaApp.Windows10.jsproj]
  CordovaApp.Windows10 -> C:\cygwin\tmp\gimlet\2334122\project\AppPackages\CordovaApp.Windows10_0.0.1.0_x86_debug_Test\CordovaApp.Windows10_0.0.1.0_x86_debug.appx
```

Also tracked in litehelpers/Cordova-sqlite-legacy-build-support#10.

This is a blocking issue for one of my clients.

**Comment by brodybits** [comment]
Sorry to be a pain but any ideas? @goya?

**Comment by goya** [comment]
the plugin might not be compatible with PhoneGap Build.  there might be another sqlite plugin that may work.

**Comment by brodybits** [comment]
Thanks @goya for the response. I would really like to find a solution for my client. Yes there are other sqlite plugins but in general they are less capable and out of date.

I think the problem is that for some reason the PhoneGap Build system does not make the normal referenced plugins directory available for the Windows build.

I really hope we can find a way to resolve this, otherwise I will be compelled to tell my customers not to use PhoneGap Build. I wonder if @vladimir-kotikov from the Microsoft Visual Studio team can help us here?

**Comment by goya** [comment]
i would suggest posting this issue on the support forum: https://forums.adobe.com/community/phonegap/build

**Comment by brodybits** [comment]
On Nov 8, 2016 5:45 PM, "Brett Rudd" <notifications@github.com> wrote:
>
> i would suggest posting this issue on the support forum:
https://forums.adobe.com/community/phonegap/build

Will do thanks @goya!

**Comment by brodybits** [comment]
I already asked in https://forums.adobe.com/thread/2230161 but got no response. I just asked again in https://forums.adobe.com/message/9123283#9123283 (maybe waiting for moderator approval). If I don't get a response I will steer my users away from PhoneGap Build and ask around for some alternatives.

**Comment by goya** [comment]
yeah not all plugins are compatible with build.  you could try using the new cli structure - http://phonegap.com/blog/2016/10/07/cli-projects-now-supported/ and see that works if they are relying on a certain directory structure only. but hopefully someone from the forum chimes in.
