### ISSUE TITLE
Launching app only displays contents of index.html?

### ISSUE THREAD

**Issue by TonyCelentano** [phonegap/build#564]
I built my app with http://build.phonegap.com/ and installed the Android .sdk on my device.

When I launch the app, it only displays the contents of index.html. It just goes straight to the index.html, it does not even show the splash screen.

I am not sure if its a problem in my config.xml, here is the link to my config: https://github.com/TonyCelentano/PinoyHoroscope/blob/master/config.xml

but I'm fairly certain I put these parts in correctly:

        <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" />
<plugin name="cordova-plugin-splashscreen" spec="~4.0.0" />

 <access origin="http://pinoyhoroscopes.com"/>

If someone could take a look over my config.xml and tell me where I did something wrong, I would greatly appreciate it :)

**Comment by ef33zy** [comment]
Hi @TonyCelentano,

**Firstly**, you need raise the issue in the PhoneGap Build Adobe forum [here](https://forums.adobe.com/community/phonegap/build).

**Secondly**, have you tried defining the preferences for using the splashcreen plugin?
In mine for example, 
```
<plugin name="cordova-plugin-splashscreen"                source="npm">
      <preference name="SplashScreen"               value="splash" />
      <preference name="AutoHideSplashScreen"       value="true" />
      <preference name="SplashScreenDelay"          value="5000" />
      <preference name="SplashMaintainAspectRatio"  value="true" />
      <preference name="FadeSplashScreen"           value="false"/>
      <preference name="ShowSplashScreenSpinner"    value="false" />
</plugin>
```

The `<preference name="SplashScreen"               value="splash" />` matches the name of my default splash screen file.

**Finally**, try putting a splash image in root folder with your `config.xml` & `index.html` files and add the tag splash: `<splash src="splash.png"/>` as suggested [here](https://forums.adobe.com/message/8894647).

**Comment by TonyCelentano** [comment]
Hi @ef33zy ,

Thanks for your help, I will test more and go to the forums you suggested if I have further problems :)

**Comment by andersborgabiro** [comment]
You might want to compare with the template I tend to use: http://abiro.com/tutorials/phonegap/
