### ISSUE TITLE
Cannot Access Build.phonegap.com

### ISSUE THREAD

**Issue by infosandhy** [phonegap/build#566]
Cannot Access Build.phonegap.com

**Comment by andersborgabiro** [comment]
Yup, the site is feeling very down at the moment, and I need to make a build today :/.

**Comment by imirs** [comment]
any updates???? i need to create a build!

**Comment by andersborgabiro** [comment]
Nope, I'm also sitting here "with my beard in the mailbox", as we for some reason say in Sweden. Stone dead. phonegap.com works, but not the sub domain.

**Comment by andersborgabiro** [comment]
I've tweeted to PhoneGap Build and PhoneGap.

**Comment by hemolyticus** [comment]
I need to  make a build :-(

**Comment by goya** [comment]
dns issue. fixed.
