### ISSUE TITLE
Phonegap app upload to App Store failed

### ISSUE THREAD

**Issue by myviridis** [phonegap/build#567]
We get 2 kinds of errors:
1. ERROR ITMS-90168: the binary you uploaded was invalid
2. You are not authorised to use this server for provider: BP3D78H39G

In the past we uploaded many apps without  this kind of errors. 

Our App Store keys are obviously still valid (until November 2017).

**Comment by goya** [comment]
what is the app id?

**Comment by myviridis** [comment]
BP3D78H39G.CalSleeper

**Comment by goya** [comment]
sorry, i meant the app id on phonegap build.

**Comment by myviridis** [comment]
![Uploading Zrzut ekranu 2016-12-16 o 09.03.59.png…]()

**Comment by myviridis** [comment]
<img width="572" alt="phonegap" src="https://cloud.githubusercontent.com/assets/6518246/21255991/d8544d38-c36f-11e6-8af2-25a1279eb5a4.png">

**Comment by goya** [comment]
1) your widget attribute "id" is currently "BP3D78H39G.CalSleeper" this should only be the reverse domain format eg. com.domainname.applicationname without the team id (BP3D78H39G)

2) plus your mobile provision should also have the same bundle identifier and has to be a production mobile provision as created on the app store developer console.

https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/AppID.html

In future please post to the support forums at https://forums.adobe.com/community/phonegap/build so we (and the community) can troubleshoot your issue.
