### ISSUE TITLE
Can't create a new project in my paid account

### ISSUE THREAD

**Issue by phaggood** [phonegap/build#568]
Getting the error 'could not access remote git repository https://github.com/myaccount/myproject.git.  Did I perhaps enter the wrong credentials in on 'Edit Account' under 'connect a github id'?  If so, how do I change it?  If I try it again it tells me that github account is already linked to a phonegap build account.

**Comment by goya** [comment]
please start a conversation at the support forums: https://forums.adobe.com/community/phonegap/build so we can troubleshoot your issue.

that github username is linked to the adobeid of el********.go@e********h.edu

you can log into build with that adobe id and unlink your github from that account and then link it to your new account.

**Comment by goya** [comment]
is this resolved were you able to access your repo?

**Comment by phaggood** [comment]
I gave up; I made a new account and asked for the old account to be deleted.
