### ISSUE TITLE
Documentation issue with android-build-tool preference

### ISSUE THREAD

**Issue by amit0001** [phonegap/build#569]
Hi,

It appears that someone did a copy-paste for the **android-build-tool** preference, from the android-minSdkVersion preference.
I tried to look it up to understand what values it can take. I think gradle is one of them but would like to understand more.

Link to said documentation:
http://docs.phonegap.com/phonegap-build/configuring/preferences/#android-build-tool

Thanks
Amit

**Comment by goya** [comment]
woah.  thanks.  fixed.
