### ISSUE TITLE
config.xml break my app

### ISSUE THREAD

**Issue by Aloxord** [phonegap/build#570]
Hello! I have a phonegap app where I need to be forced to look upright, and I did! But a few weeks ago, I started to malfunction and after many laps I discovered that removing the config.xml worked, my phonegap version is the last and the id is 2416744

**Comment by goya** [comment]
please post an issue on our support forums: https://forums.adobe.com/community/phonegap/build

be sure to include the config.xml that is causing the issue in the post.
