### ISSUE TITLE
"The binary you uploaded was invalid."

### ISSUE THREAD

**Issue by johny99** [phonegap/build#574]
Got the following error: "The binary you uploaded was invalid." when uploading the phone gap file to the Apple (via iTunes connect) any idea what can be the issue?

[metadata.xml, Grendz-2.ipa]
[2017-01-24 19:38:05 JST] <main> DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[2017-01-24 19:38:05 JST] <main> ERROR: ERROR ITMS-90168: "The binary you uploaded was invalid."
[2017-01-24 19:38:05 JST] <main> DBG-X: The error code is: 1102
[2017-01-24 19:38:05 JST] <main>  INFO: Done performing authentication.
[2017-01-24 19:38:05 JST] <main> DBG-X: Returning 1

Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/tj/795m8r7n683d60kzff15nb2c0000gn/T/76BF2049-BA58-4967-8D4A-02F8DBDA6E6F/1187117482.itmsp - Error Messages:
		ERROR ITMS-90168: "The binary you uploaded was invalid."

**Comment by ronnievdc** [comment]
Today I got the same issue.
I found this post on Stackoverfow http://stackoverflow.com/a/32987261 but didn't help.

After removing the folder uploading worked again:
`rm -R ~/.itmstransporter`

**Comment by tisdall** [comment]
for anyone else coming here...  I found that despite iTunes Connect suggesting using Application Loader 3.0, it simply doesn't work.  I had to download Xcode and use the 3.6 version that came with it to upload properly.

**Comment by peni4142** [comment]
is there a way without downloading Xcode? my Mac can't download that
