### ISSUE TITLE
Missing Info.plist key : NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by EdwinRikkers** [phonegap/build#576]
When uploading the app build by PhoneGap Build to Itunes Connect I get the following error from ITunes Connect:
Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

I already added the following to my config.xml but no result:
```
<gap:config-file platform="ios" parent="NSPhotoLibraryUsageDescription" overwrite="true">
        <string>For uploading photos from the library</string>
</gap:config-file>
```

**Comment by goya** [comment]
the text of the gap:config node should be valid plist xml eg.

**<string>For uploading photos from the library</string>**

**Comment by EdwinRikkers** [comment]
I see now that my copy/paste into this forum removed the `<string>` tag. The `<string>` tag is actually there.

**Comment by goya** [comment]
please open a topic on our support forums for app related issues: https://forums.adobe.com/community/phonegap/build

please include the app id # of the app with the issue. if a forum support issue already exists please paste a link to it here so we can troubleshoot.

**Comment by ronnievdc** [comment]
You can define the NSPhotoLibraryUsageDescription in the cordova-plugin-camera tag.

```
<plugin name="cordova-plugin-camera" version="2.3.0" source="npm">
    <variable name="CAMERA_USAGE_DESCRIPTION" value="For uploading photos from the library" />
    <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="For uploading photos from the library" />
</plugin>
```

**Comment by EdwinRikkers** [comment]
fixed the issue by:

```
<config-file platform="ios" parent="NSPhotoLibraryUsageDescription" mode="replace">
        <string>For uploading photos from the library</string>
    </config-file>
```
