### ISSUE TITLE
Hydration preventing deviceready from firing

### ISSUE THREAD

**Issue by kwlayman** [phonegap/build#583]
When I enable Hydration on Phonegap Build the deviceready event does not fire. Hydration is awesome but if it disables the ability to init plugins what is the point? There is an unresolved post on stackoverflow about this very issue from 3 years ago? Am I just a dumbass missing something here (distinct possibility)? See last comment here: http://stackoverflow.com/questions/24109528/deviceready-not-firing-on-phonegap-build-bd/24113587

FYI I am only deploying on Android.

**Comment by wildabeast** [comment]
Can you open a discussion here please:

https://forums.adobe.com/community/phonegap/build

**Comment by wildabeast** [comment]
Closing in favour of above forum thread.
