### ISSUE TITLE
Error: upload failed; please try again [2]

### ISSUE THREAD

**Issue by rxtcreagh** [phonegap/build#584]
for the last 90 minutes I've been unable to upload a new version of the code.
Has anyone been able to upload new versions to PhoneGap? I get the following error

Error: upload failed; please try again [2]

**Comment by goya** [comment]
error code 2 is a generic zip format error.  what platform are you on, i recommend zipping up your app again.

**Comment by rxtcreagh** [comment]
Hi, thank you for replying. We are using windows and using the same files we always use. It was working fine earlier this morning. I've tried using 7-zip, Windows built-in zip and rar. They all fail. I've also tried from different machines.

**Comment by shri-aithal** [comment]
I too have the same issue that I'm seeing today. I read somewhere creating a new app fixed the issue for someone. I created a new app and the upload succeeded, but the resulting binaries for Windows and Android were missing some folders making the binaries unusable.

Uploading the source again in the new app causes the same error.

I'm using 7-zip on a Windows machine to create the zip file (which has been working all along)

**Comment by goya** [comment]
is there any weird permissions on the files or symbolic links to orphaned or files outside the zip?

**Comment by shri-aithal** [comment]
I found the reason why I had the error. The structure of my uploaded zip file was
```
Project Root
|-- res
|-- www
|-- config.xml
```

I recently started using Visual Studio for working on the source. Visual Studio added a "native\windows" folder under "res" where it stored windows signing keys. When I uploaded the zip file containing "res\native", it gave error 2. After that happened, even uploading a file without native folder caused the same issue. 

I created a new app and was able to reproduce the same error. As a work around, I delete the app that had the issue and created a new one. I'm excluding native folder from my uploads in the new app. 

There appears to be a problem with PhoneGap Build, which makes it retain the files from a previous upload.

**Comment by goya** [comment]
so your upload issue is resolved?

**Comment by shri-aithal** [comment]
After my last post I've had the same error a couple of times, but in general it seems to be working. But I believe some investigation is needed to find out why Phonegap Build is remembering an old upload and making the app unusable if an upload is bad.
