### ISSUE TITLE
Unable to update Signing Key via the PhoneGap API

### ISSUE THREAD

**Issue by ctdany86** [phonegap/build#587]
Hi,

I have been trying for long time to unlock my iOS/Android key via the PhoeGap API but it doesn't work.
This is the function I call as soon as I am successfully authenticate: 

     function unlockAndroidKeyMethod(api){
       var androidKeyId = 123456
       var unlockAndroidKeyForm = {
           form: {
               data: {
                   key_pw: "passwd123456",
                   keystore_pw: "passwd123456"
               }
            }
       };
       api.put('/api/v1/keys/android/' + androidKeyId, unlockAndroidKeyForm);
     }

After my build is completed I print out what I get back for the build API and it says the keys are locked:

     .....
     status: { android: 'error', ios: 'error', winphone: 'complete' },
     phonegap_versions: { android: '6.1.0', ios: '4.3.0', winphone: '4.4.3' },
     download: { winphone: '/api/v1/apps/2560475/winphone' },
     error:
       {
            android: 'android signing key is locked',
            ios: 'ios signing key is locked'
        },
      ....
`

what am I doing wrong?
Thanks

**Comment by goya** [comment]
what response and status code do you get back from the put request to unlock the key?

please start an issue at https://forums.adobe.com/community/phonegap/build so we can troubleshoot

**Comment by wildabeast** [comment]
What response do you get from your put request to unlock the key?
