### ISSUE TITLE
The following build commands failed: CopyPlistFile

### ISSUE THREAD

**Issue by dahannajr** [phonegap/build#590]
We've started receiving the above error intermittently (more often then not though).  This problem began when we added a custom custom Plugin to copy to the GoogleService-Info.plist file required by Firebase Cloud Messaging.
 
Android is building and running fine.  Please note, that the build sometimes does work in PhoneGap Build and sometimes doesn't.  The log file and plugin.xml file are attached.

[build-log.txt](https://github.com/phonegap/build/files/926606/build-log.txt)
[plist-plugin.zip](https://github.com/phonegap/build/files/926608/plist-plugin.zip)

Original Entry: https://forums.adobe.com/thread/2304185

**Comment by wildabeast** [comment]
Having a look -- going to close this and discuss in the forum thread.
