### ISSUE TITLE
Error - the password for the associated certificate is incorrect - You can fix this here

### ISSUE THREAD

**Issue by lifecup** [phonegap/build#592]
hi

we can not build IOS app in phonegap

why ???

Error - the password for the associated certificate is incorrect - You can fix this here

password is OK but i see this error

thanks

**Comment by goya** [comment]
please start a discussion at https://forums.adobe.com/community/phonegap/build

**Comment by djanowski** [comment]
When you export the p12 file, make sure to select both the private key **and** the certificate.

![screen shot 2018-05-29 at 15 22 34](https://user-images.githubusercontent.com/2268/40677592-7807dd38-6354-11e8-8402-7fed7d8f943c.png)
