### ISSUE TITLE
Id : framework not found

### ISSUE THREAD

**Issue by edvenkat** [phonegap/build#593]
Please advice on this error

> Ld /Users/phonegap/Library/Developer/Xcode/DerivedData/PocCommon-ctlfczaxzyhuupbwlnhvsjpsmbji/Build/Intermediates/ArchiveIntermediates/PocCommon/IntermediateBuildFilesPath/PocCommon.build/Release-iphoneos/PocCommon.build/Objects-normal/arm64/PocCommon normal arm64
>     cd /tmp/gimlet/2567854/project
>     export IPHONEOS_DEPLOYMENT_TARGET=8.0
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -L/tmp/gimlet/2567854/project/build -F/tmp/gimlet/2567854/project/build -FPocCommon/Plugins/com.xtify.mce.sdk -filelist /Users/phonegap/Library/Developer/Xcode/DerivedData/PocCommon-ctlfczaxzyhuupbwlnhvsjpsmbji/Build/Intermediates/ArchiveIntermediates/PocCommon/IntermediateBuildFilesPath/PocCommon.build/Release-iphoneos/PocCommon.build/Objects-normal/arm64/PocCommon.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/phonegap/Library/Developer/Xcode/DerivedData/PocCommon-ctlfczaxzyhuupbwlnhvsjpsmbji/Build/Intermediates/ArchiveIntermediates/PocCommon/IntermediateBuildFilesPath/PocCommon.build/Release-iphoneos/PocCommon.build/Objects-normal/arm64/PocCommon_lto.o -fobjc-arc -fobjc-link-runtime -ObjC /tmp/gimlet/2567854/project/build/libCordova.a -lz -framework IBMMobilePush -framework CoreTelephony -framework CoreLocation -lsqlite3 -Xlinker -dependency_info -Xlinker /Users/phonegap/Library/Developer/Xcode/DerivedData/PocCommon-ctlfczaxzyhuupbwlnhvsjpsmbji/Build/Intermediates/ArchiveIntermediates/PocCommon/IntermediateBuildFilesPath/PocCommon.build/Release-iphoneos/PocCommon.build/Objects-normal/arm64/PocCommon_dependency_info.dat -o /Users/phonegap/Library/Developer/Xcode/DerivedData/PocCommon-ctlfczaxzyhuupbwlnhvsjpsmbji/Build/Intermediates/ArchiveIntermediates/PocCommon/IntermediateBuildFilesPath/PocCommon.build/Release-iphoneos/PocCommon.build/Objects-normal/arm64/PocCommon
> ld: framework not found IBMMobilePush
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

>

**Comment by goya** [comment]
please start an issue at https://forums.adobe.com/community/phonegap/build for issues with specific app errors. this is for build service features, not user support.
