### ISSUE TITLE
you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager, On rebuild i got this issue.

### ISSUE THREAD

**Issue by pvantage** [phonegap/build#596]
Build Date: 2017-06-13 08:57:20 +0000
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.255 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [SDK Patch Applier v4, Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by eyalkatz** [comment]
I get this error now when I use the phonegap build online compiler. Is there anything that I can do to accept this license? or is that bug with the online compiler system?

**Comment by eyalkatz** [comment]
This error suddenly appeared using the same project as before, only for Android.

**Comment by goya** [comment]
this appears when google releases a new version of the support library.  there is a lag between the release and our support as we test the new version as google has a habit of breaking things.

we get notified when this occurs and typically it will get updated within maybe 3 days.

**Comment by ericoporto** [comment]
how do I accept the license agreement when doing `phonegap build android` locally?

**Comment by nicksterFL** [comment]
what is the resolution to this issue? I have the same error asking to accept license agreement.

**Comment by alexcatanet** [comment]
Open your cmd and write:

C:\Users\userName>AppData\Local\Android\Sdk\tools\bin\sdkmanager --licenses
After, don't forget to insert 'y' - accept the licenses
That's all!

After you had accepted all the licenses and will try to repeat the same procedure, you should get the next message in your command prompt:

**All SDK package licenses accepted.======] 100% Computing updates...**

**Comment by JakenHerman** [comment]
This solution does not work. 100% accepted, still get the error. I've accepted all licenses at my directory `C:\Users\<UserName>\AppData\Local\Android\sdk\tools\bin\` as well as all of the licenses in `C:\Program Files (x86)\Android\android-sdk\tools\bin`.

**Comment by Topstar2ng** [comment]
Same problem I'm having. I have run the command to accept all licenses. 100% accepted but still showing same error. I have also installed about everything under the Android SDK tools, still error persist!

**Comment by opexzy** [comment]
Same problem here, i have install all the licenses, still error persist

**Comment by exenin** [comment]
Ensure that you have the correct versions - match them up
`  [SDK Patch Applier v4, Android SDK Platform 26, Android Emulator, Android SDK Platform-Tools, Android SDK Tools, Android SDK Build-Tools 26.0.2].
`

Double click the Item on the SDK manager and you will see you can install different versions

**Comment by cjwhitsitt** [comment]
You may need to open the SDK manager and install the items it mentions. For me, they hadn't been installed at all. Doing that resolved the issues.

**Comment by zoobibackups** [comment]
done all the things. but smae issue
