### ISSUE TITLE
Windows builds do not have correct version number

### ISSUE THREAD

**Issue by MeirBon** [phonegap/build#597]
#### This is a replication of [issue Phonegap-cli-725](https://github.com/phonegap/phonegap-cli/issues/725).

When building an app and specifying the following in config.xml:
```
<widget xmlns="http://www.w3.org/ns/widgets"
        xmlns:gap="http://phonegap.com/ns/1.0"
        windows-packageVersion="2.0.47"
        version="2.0.47"
        versionCode="2047000">
```
we expect to build a 2.0.47 version of the app.

A version 2.0.47 build is created for Android and iOS, but for Windows 10 a 2.0.4.0 build is created instead of a 2.0.47. The app works, but versioning is wrong. Adding or removing windows-packageVersion does not change the outcome.

Building apps locally using only Cordova produces builds with correct versioning.

#### This issue is also described in the [forums](https://forums.adobe.com/message/9247410#9247410).

**Comment by goya** [comment]
this should be fixed. 

1) it was a windows phone 8 requirement that has long since been removed.
2) we never supported the windows-packageVersion attribute

**Comment by MeirBon** [comment]
Cannot check if this was fixed, we now get the following error when building: 
```
COMPILE OUTPUT
--------------------------------------------------------------------------------
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.
```
This was not the case before creating this issue. The app would get build, but would have the incorrect version.

I know windows-packageVersion was never supported, but I added it to the XML as it is a config option in Cordova and was hoping it would be picked up by the build-server. In the end windows-packageVersion should not be necessary.
