### ISSUE TITLE
Unable to unlock using write API

### ISSUE THREAD

**Issue by Criccle** [phonegap/build#599]
I am trying to unlock my Android key using the write API.  For some reason I only receive information on the locked status, instead of being able to unlock it using the API.

**Comment by goya** [comment]
key unlock docs are here: http://docs.phonegap.com/phonegap-build/developer-api/write/#-put-https-build-phonegap-com-api-v1-keys-platform-id-

please start an issue on the support forums (https://forums.adobe.com/community/phonegap/build) if you are having trouble using the api
