### ISSUE TITLE
[Android|IOS] Revisit Viewports

### ISSUE THREAD

**Issue by hardeep** [phonegap/build#60]
More information available here:

http://community.phonegap.com/nitobi/topics/proof_viewport_meta_tag_ignored

**Comment by NibbleByte** [comment]
Meta tag is still ignored in Android.
This is how I've solved it: http://stackoverflow.com/a/28755743/4612666
Basically change the AndroidManifest.xml min/target version to this:
<uses-sdk android:minSdkVersion="7" />

Can play with the version, not really sure.

**Comment by JohnHanks** [comment]
I want to reopen this issue.  This is not solved.

**Comment by sonstiges** [comment]
still not solved....
