### ISSUE TITLE
When compile my build in Phonegap i can not get a release build?

### ISSUE THREAD

**Issue by KamalSalah** [phonegap/build#600]
How do i make a build that is not debug i have not checked the debugmode ??

I trying to publish it on android and it says it is a debugmode i download the apk from phonegap build and the file named as debugg ..

Somthing is wrong what do i do wrong?

**Comment by goya** [comment]
you must sign the android build with a signing key for a release build.

**Comment by KamalSalah** [comment]
Okey Goya Thanks, I am new at Andoid market so I have make an account on Andoid Development area. so i make a signing key there or?

Have you any tuturial for that? or where to look?

I try to search see what i find

**Comment by goya** [comment]
https://developer.android.com/studio/publish/app-signing.html#cert

there is documentation for creating the signing key on windows here: http://docs.phonegap.com/phonegap-build/signing/android/
