### ISSUE TITLE
build.phonegap.com Error

### ISSUE THREAD

**Issue by imadige** [phonegap/build#603]
He's been making an error for a week.

https://build.phonegap.com/apps/2678522/builds

<gap:plugin name="jum.toast" source="pgb" />

Error - Plugin error (you probably need to remove plugin files from your app): Installing "jum.toast" at "2.5.1" for ios Failed to install 'jum.toast': Error: Your ios platform does not have Api.js at Object.getPlatformApiFunction (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/cordova/util.js:489:19) at Object.getPlatformApi (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/platforms/platforms.js:56:25) at handleInstall (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:618:29) at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:386:24 at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44 at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at _combinedTickCallback (internal/process/next_tick.js:95:7) Your ios platform does not have Api.js - You can fix this here

**Comment by goya** [comment]
for support issues for individual apps please start a conversation at https://forums.adobe.com/community/phonegap/build
