### ISSUE TITLE
PhoneGap Build

### ISSUE THREAD

**Issue by winer222** [phonegap/build#604]
For some reason the phonegap build website is claiming that I have two projects already submitted but those projects where never submitted by me and also do not appear on my github account.

![image](https://user-images.githubusercontent.com/994583/29772321-957e8968-8bf8-11e7-8be1-3eabd0af1671.png)
Phone Gap Build

![image](https://user-images.githubusercontent.com/994583/29772385-d7b02224-8bf8-11e7-9f6c-b039b48faa9c.png)
Github

**Comment by goya** [comment]
those apps were added and built in 2013. 

they are from a free github repository so they dont have to be in your github account.
