### ISSUE TITLE
cli-7.0.1 iOS build fails when app name contains whitespace.

### ISSUE THREAD

**Issue by kleeb** [phonegap/build#605]
When you put an app name in the config.xml, that contains whitespaces, the iOS build won't be downloaded with this error:
 
ERROR org.apache.commons.httpclient.InvalidRedirectLocationException: Invalid redirect location: http://s3.amazonaws.com/ios.phonegap/production/apps/cddbfbd0-8ee9-11e7-9d06-065de4f94672/some app name.ipa
 
 
clearing out whitespaces fixes it.
Its not occuring on 6.5.0. Not occuring on Android only builds.

**Comment by wildabeast** [comment]
[Forum discussion here.](https://forums.adobe.com/thread/2377921)

Closing this unless we decide it is actually a bug with PGB.
