### ISSUE TITLE
Unable to update IOS Info.plist file using Phonegap build

### ISSUE THREAD

**Issue by 007-surajit** [phonegap/build#607]
I am unable to edit the Info.plist file using the below code in config.xml

```
<config-file platform="ios" parent="UIBackgroundModes">
        <array>
			<string>remote-notification</string>
		</array>
</config-file>
```

**Comment by wildabeast** [comment]
Please open a thread in the forum:

https://forums.adobe.com/community/phonegap/build

Include the phonegap-version you are using, and your App ID.
