### ISSUE TITLE
Phonegap app build malformed config.xml  issue coming

### ISSUE THREAD

**Issue by suvamchikun** [phonegap/build#611]
Am using the below config file,But its comming error malformed config.xml

<?xml version="1.0" encoding="utf-8" ?>
<widget xmlns = "http://www.w3.org/ns/widgets"
    xmlns:gap = "http://phonegap.com/ns/1.0"
    xmlns:android = "http://schemas.android.com/apk/res/android"
    id        = "bgf.mobile.app"
    version   = "1.3.3">
    <name>Big Foodys</name>
    <description>
Big Foodys    </description>
    <author email="subhakantrout@gmail.com" href="http://bigfoodys.com"></auther>

    <icon src="icon.png" />           
    <content src="index.html" />
               
	<preference name="orientation" value="portrait" />
	<preference name="android-build-tool" value="gradle" />
	<preference name="permissions" value="none"/>	
		
	<gap:plugin name="cordova-plugin-whitelist" source="npm" />
    <gap:plugin name="phonegap-plugin-push" source="npm" spec="1.5.3" />
    <gap:plugin name="cordova-plugin-device" source="npm"  />		
	<gap:plugin name="cordova-plugin-inappbrowser" source="npm"  />		
	<gap:plugin name="cordova-plugin-splashscreen"source="npm"  />	
	<gap:plugin name="cordova-plugin-geolocation"source="npm"  />
	<gap:plugin name="cordova-plugin-network-information" source="npm" />
	<plugin name="com.paypal.cordova.mobilesdk" spec="3.1.2" source="pgb" />

		
	<gap:plugin name="cordova-plugin-fastrde-checkgps" source="npm" />
	<gap:plugin spec="https://github.com/rodrigo-martinezd/cordova-dialog-gps.git" source="git" />

	<gap:splash src="splash.png" />
	<preference name="AutoHideSplashScreen" value="false" />  	
    <preference name="SplashScreenDelay" value="10000" />    
    <preference name="fullscreen" value="false" />
	
    <access origin="*" />
       
    <gap:config-file platform="android" parent="/manifest">
        <supports-screens android:xlargeScreens="true" android:largeScreens="true" android:smallScreens="true" />
        <application android:theme="@android:style/Theme.NoTitleBar" >            
        </application>
    </gap:config-file>    
    
</widget>

**Comment by suvamchikun** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<widget xmlns = "http://www.w3.org/ns/widgets"
    xmlns:gap = "http://phonegap.com/ns/1.0"
    xmlns:android = "http://schemas.android.com/apk/res/android"
    id        = "bgf.mobile.app"
    version   = "1.3.3">
    <name>Big Foodys</name>
    <description>
Big Foodys    </description>
    <author email="subhakantrout@gmail.com" href="http://bigfoodys.com"></auther>

    <icon src="icon.png" />           
    <content src="index.html" />
               
	<preference name="orientation" value="portrait" />
	<preference name="android-build-tool" value="gradle" />
	<preference name="permissions" value="none"/>	
		
	<gap:plugin name="cordova-plugin-whitelist" source="npm" />
    <gap:plugin name="phonegap-plugin-push" source="npm" spec="1.5.3" />
    <gap:plugin name="cordova-plugin-device" source="npm"  />		
	<gap:plugin name="cordova-plugin-inappbrowser" source="npm"  />		
	<gap:plugin name="cordova-plugin-splashscreen"source="npm"  />	
	<gap:plugin name="cordova-plugin-geolocation"source="npm"  />
	<gap:plugin name="cordova-plugin-network-information" source="npm" />
	<plugin name="com.paypal.cordova.mobilesdk" spec="3.1.2" source="pgb" />

		
	<gap:plugin name="cordova-plugin-fastrde-checkgps" source="npm" />
	<gap:plugin spec="https://github.com/rodrigo-martinezd/cordova-dialog-gps.git" source="git" />

	<gap:splash src="splash.png" />
	<preference name="AutoHideSplashScreen" value="false" />  	
    <preference name="SplashScreenDelay" value="10000" />    
    <preference name="fullscreen" value="false" />
	
    <access origin="*" />
       
    <gap:config-file platform="android" parent="/manifest">
        <supports-screens android:xlargeScreens="true" android:largeScreens="true" android:smallScreens="true" />
        <application android:theme="@android:style/Theme.NoTitleBar" >            
        </application>
    </gap:config-file>    
    
</widget>

**Comment by goya** [comment]
paste your config.xml here: https://www.xmlvalidation.com/ 

that will validate the xml. it might be a missing namespace etc.

for specific issues like this please post an issue in our support forums: https://forums.adobe.com/community/phonegap/build
