### ISSUE TITLE
cli-7.1.0 (and newer)?

### ISSUE THREAD

**Issue by andersborgabiro** [phonegap/build#616]
Here's the related (still unanswered) forum post that explains the issues: https://forums.adobe.com/thread/2419370

Here's another one that seems related (reverting to an older version fixes the problem):
https://forums.adobe.com/message/10078800

In short: We (developers) need much quicker turn-around on support for new Cordova versions. As pointed out in the first post, 2 weeks should be enough to deploy a new vanilla Cordova version. cli-7.0.1 was officially available > 4 months ago. You do the math.

Regards,
Anders

**Comment by avanrossum** [comment]
Seconded.  The complete lack of information regarding this issue is incredibly frustrating as well.

**Comment by uchida-nunet** [comment]
+1

I'm paid Adobe PhoneGap Build subscriber. I'm concerned by the VERY LONG times before newer versions are supported.  No one quickly action and even answer from Adobe.

**Comment by goya** [comment]
xcode9 is up
