### ISSUE TITLE
Can't edit CFBundleShortVersionString with cli-7.1.0

### ISSUE THREAD

**Issue by scottopolis** [phonegap/build#620]
With the new builder since cli-7.0.1 you are supposed to be able to use the edit-config element to make changes to the Info.plist file for iOS.  This does not work with CFBundleShortVersionString.

My config.xml code:

    <platform name="ios">

    <edit-config target="CFBundleShortVersionString" file="*-Info.plist"  mode="merge">

    <string>100</string>

    </edit-config>

    </platform>

Resulting Info.plist file uses the widget version, which in my case is 1.0.0.

My PG Build app ID is 2975868

**Comment by scottopolis** [comment]
Nevermind, this works if you move it outside the platform tag. Doesn't make sense, but at least it works now.

**Comment by andersborgabiro** [comment]
Just wondering: Why do you need this setting? I've never used it.
