### ISSUE TITLE
With PG CLI 8.0 (not 7.1) a large number of files displays a successful Android build as errorred (No pb with iOS and Windows)

### ISSUE THREAD

**Issue by jlchereau** [phonegap/build#623]
Please check https://forums.adobe.com/thread/2442942

My App Id is https://build.phonegap.com/apps/2391592
Source code is available at https://github.com/kidoju/Kidoju-Mobile

The App builds perfectly with PG CLI 7.1.0.
The Android build is successful but shown as errroed with PG CLI 8.0.0.

As kindly discovered by @jcesarmobile_ in adobe forums, PG CLI 8.0.0 is not happy with the number of files my app packages on Phonegap build.

**Comment by goya** [comment]
should be fixed. was side effect after a gradle upgrade in cordova.

**Comment by jcesarmobile** [comment]
I confirm it's building fine now.
But now I'm getting failure for iOS with just this message:

> Build Date: 2018-02-11 07:37:24 -0800

**Comment by jlchereau** [comment]
I have experienced the same in the past even with previous CLI versions.
Clicking the Rebuild button generally gets you there.
