### ISSUE TITLE
Signing certificate has expired with a new certificate 

### ISSUE THREAD

**Issue by Juan-dev** [phonegap/build#625]
My original certificate was expired. I created a new one and linked to my provisioning profile. 
 
My provisioning profile expires on Feb 20, 2019.
My signing certificate expires on Feb 19, 2019. 
 
When I upload my Provisioning file and certificate to PhoneGap, I click the padlock icon to unlock the key with the password and the padlock changes colour to grey letting me know that the key is unlocked. 
 
When I try to build my app for iOS I get the message: Error - Signing certificate has expired - You can fix this here
Log: Build Date: 2018-02-19 22:05:04 -0800
 
I realized that I am getting that same error no matters what I have in my Settings Key:
- Removing the key (no keys). I get that message.
- If I unlock my key with a random text as password ( not the actual password). The padlock changes the colour and indicates the key is unlocked. When I try to build my app I get the same error message: Error - Signing certificate has expired - You can fix this here

**Comment by wildabeast** [comment]
Hi can you ask this in [the PGB support forum](https://forums.adobe.com/community/phonegap/build)? Please use the same Adobe ID that you use to log into PhoneGap Build so we can associate your account.

**Comment by Juan-dev** [comment]
I did! no answers so far.

**Comment by wildabeast** [comment]
OK just found your post, will check it out.
