### ISSUE TITLE
Can't use custom fonts in iOS app (get submission error)

### ISSUE THREAD

**Issue by heathercash** [phonegap/build#656]
I'm using the latest version of PhoneGap (CLI 9.0.0) and I'm using custom fonts in my project by including the font files in a folder and calling them from my css file. The app works great but after submitting to the App Store I get the following error in an email:

`ITMS-90807: Invalid entitlement - The com.apple.developer.user-fonts is valid only for apps build with SDK 13 or later.`

I have searched & posted on forums, and updated XCode Application Loader.

Is there anything I can enter into my config.xml file so that SDK 13 or later is used? Or do I need to remove my custom fonts from my project?

Thanks

**Comment by goya** [comment]
sdk 13 is still in beta and won’t be supported on phonegap build until it is out of beta and we have been able to test it in our build environments and also test cordova compatibility.

**Comment by heathercash** [comment]
Thanks for the response! So in the meantime, I'll just need to remove my custom fonts from my project?

**Comment by goya** [comment]
yeah for the time being yes. we’ll blog and add a notification when phonegap build is updated.
