### ISSUE TITLE
Builder is not working.

### ISSUE THREAD

**Issue by 106firestarter** [phonegap/build#664]
Hey guys, I'm sorry to open an issue for this, but there's no other way to contact you about this.

Since this morning (6april, monday) the builder is not working properly. I can't upload things and I see alot of AWS permission errors on the devtools. For instance, the page doesn't load the app icons or the support documentation, due to those permission erros. So, I guess there must be something to do with that. However, everything was working fine last friday (3 april).

Could you please investigate this issue? 

Thanks in advance!

**Comment by andersborgabiro** [comment]
To verify this I viewed the site a few minutes ago, together with phonegap remote, and it worked fine. Maybe they fixed it in the meantime.

phonegap remote still generates an error (Callback must be a function), but that's been the case for a year or so.

**Comment by 106firestarter** [comment]
I can confirm this!! It is working properly now!

I don't know what was the issue, but there are no error messages from AWS s3 now. Should be fixed.

Thank you for the heads-up @andersborgabiro !!
