### ISSUE TITLE
Configure UIBackgroundModes 

### ISSUE THREAD

**Issue by zh25** [phonegap/build#67]
Need a way to set the plist equivalent of:

UIBackgroundModes=location

Which will enable background GPS tracking.

**Comment by iconico** [comment]
Does the config file addition support location as well as audio? I'm assuming yes, and if so is this correct?

    <gap:config-file platform="ios" parent="UIBackgroundModes" overwrite="true">
        <array>
            <string>location</string>
        </array>
    </gap:config-file>

Also how do I do both audio and location?

**Comment by DanielHindi** [comment]
`<gap:config-file platform="ios" parent="UIBackgroundModes" overwrite="true">
        <array>
            <string>audio</string>
            <string>location</string>
        </array>
    </gap:config-file>`

**Comment by iconico** [comment]
Thanks Daniel!

I see several 3rd party plugins in the PhoneGap Build Repo for enabling background location services here:
https://build.phonegap.com/plugins

I'm wondering if adding the above config file tag is enough, or should I be using a plugin like this one?
https://github.com/firassouki/com.cleartag.plugins.EnableBackgroundLocation

**Comment by DanielHindi** [comment]
Really depends on what you are planning on doing with the information. If you are looking to check periodically on the device location (could be draining on the battery) or do you want to tap into lower level tracking like geo-fencing where you just want large changes in location

If you want simple checking ever few second you can use what you have. If you want something more aggressive without draining the battery maybe you'd be better served with plugins

**Comment by iconico** [comment]
Basically I just want to check every 30 seconds to see if the user has moved more than 200 meters from a single point.
I was using navigator.geolocation.watchPosition() and it works fine in Android.
Any advice appreciated.

**Comment by DanielHindi** [comment]
this probably should be on a separate thread (before anyone complains). What you have above should work just fine. Are you facing problems? Make sure you import the core GPS plugin and request permission in your config.xml and you should be good to go

**Comment by iconico** [comment]
Works fine in Android and in iOS when the app is running.
I'll rebuild with that config.xml change. Thanks

**Comment by wworley** [comment]
This might be helpful to someone searching around, it describes all the UIBackgroundModes
https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW22
