### ISSUE TITLE
[Portal] Unable to choose default key.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#80]
User was unable to choose default key from account setting page. Radio button only appear at the first row.

Tested and verified on Chrome, Firefox and IE

![image](https://f.cloud.github.com/assets/995594/85658/45a8997e-6470-11e2-9b0a-3839790efd1d.png)

Related issue:
http://community.phonegap.com/nitobi/topics/key_unlocking_panel

**Comment by amirudin** [comment]
@wildabeast Request reopen.

Still reproducible.
![adhoc](https://cloud.githubusercontent.com/assets/995594/5641215/d868b014-966e-11e4-96e8-c48cfa575200.png)

**Comment by Pevisha** [comment]
@amirudin How long do you think this issue would take to fix? 

Thank you.

**Comment by wildabeast** [comment]
@Pevisha this isn't blocking you is it? You should still be able to select that key in the app details view:

![screen shot 2015-01-07 at 12 34 25 pm](https://cloud.githubusercontent.com/assets/118985/5652848/b1cd75ac-9669-11e4-803a-c6a9f9255fcc.png)

**Comment by Pevisha** [comment]
@wildabeast, Thanks!
I had no idea it could be done this way. I am still fairly new at this.

Thank you again!
