### ISSUE TITLE
Write API for set key as default

### ISSUE THREAD

**Issue by destitutus** [phonegap/build#89]
Unlocking key with request
<code>curl -u andrew.lunny@nitobi.com 
-d 'data={"password":"password1"}' 
-X PUT https://build.phonegap.com/api/v1/keys/ios/11</code>
work fine, but I can not find a way set key as default.
I try same 
<code>curl -u andrew.lunny@nitobi.com 
-d 'data={"password":"password1", "default":"true"}' 
-X PUT https://build.phonegap.com/api/v1/keys/ios/11</code>
but it request fail.
Is a way for set key as default?

**Comment by josefran** [comment]
Hi, 

when are you fixed this feature? This situation break our continuous delivery, because we need change manually the default key.

Thanks

**Comment by mdevlin821** [comment]
Has this issue been corrected ?

**Comment by goya** [comment]
'default' added to api
