### ISSUE TITLE
Lack of settings for Android Theme

### ISSUE THREAD

**Issue by davidhampgonsalves** [phonegap/build#97]
There is currently no settings(in config.xml) to prevent the black screen and titlebar from showing when Phonegap apps built with Phonegap Build launch on Android before the splash image displays. 

In the android manifest this would be solved by setting the applications theme to: notitlebar

The existing fullscreen attribute doesn't address or solve this issue.

Documented by another user here: http://community.phonegap.com/nitobi/topics/can_i_set_notitlebar_for_the_android_build_to_prevent_the_titlebar_from_flashing_before_the_splash_screen

**Comment by VijayAmirtharaj106** [comment]
Hi,
Even after adding the above lines of code, Phonegap build still shows error. My App ID is 1800535
